const carPool = [
  { id: 1  , name: "16 Angels"                      , category: "versatile"  , released: true  },
  { id: 2  , name: "16 Angels STH"                  , category: "versatile"  , released: true  },
  { id: 3  , name: "2001 Mini Cooper"               , category: "versatile"  , released: false },
  { id: 4  , name: "2020 Corvette"                  , category: "speeder"    , released: true  },
  { id: 5  , name: "2020 Corvette STH"              , category: "versatile"  , released: true  },
  { id: 6  , name: "24 Ours"                        , category: "speeder"    , released: true  },
  { id: 7  , name: "24 Seven"                       , category: "drifter"    , released: true  },
  { id: 8  , name: "40 Somethin"                    , category: "versatile"  , released: true  },
  { id: 9  , name: "5 Alarm"                        , category: "titan"      , released: true  },
  { id: 10 , name: "91 BMW M3"                      , category: "drifter"    , released: false },
  { id: 11 , name: "91 Mazda Miata MX5"             , category: "drifter"    , released: true  },
  { id: 12 , name: "91 Mazda Miata MX5 STH"         , category: "versatile"  , released: true  },
  { id: 13 , name: "91 Mercedes Benz G-Class"       , category: "titan"      , released: false },
  { id: 14 , name: "98 Subaru Impreza"              , category: "drifter"    , released: false },
  { id: 15 , name: "Aeroflash"                      , category: "speeder"    , released: false },
  { id: 16 , name: "Alfa Romeo 155 V6"              , category: "speeder"    , released: true  },
  { id: 17 , name: "Alfa Romeo Giulia"              , category: "versatile"  , released: false },
  { id: 18 , name: "Anthracite"                     , category: "speeder"    , released: true  },
  { id: 19 , name: "Aristo Rat"                     , category: "speeder"    , released: true  },
  { id: 20 , name: "Aston Martin DBS"               , category: "speeder"    , released: false },
  { id: 21 , name: "Aston Martin Vulcan"            , category: "speeder"    , released: true  },
  { id: 22 , name: "Audi R8 LMS"                    , category: "speeder"    , released: false },
  { id: 23 , name: "Audi RS5 Coupe"                 , category: "versatile"  , released: true  },
  { id: 24 , name: "Audi Sport Quattro"             , category: "versatile"  , released: true  },
  { id: 25 , name: "Backdraft"                      , category: "versatile"  , released: true  },
  { id: 26 , name: "Bad to the Blade"               , category: "speeder"    , released: true  },
  { id: 27 , name: "Baja Bison"                     , category: "titan"      , released: true  },
  { id: 28 , name: "Baja Bone Shaker"               , category: "titan"      , released: false },
  { id: 29 , name: "Baja Truck"                     , category: "titan"      , released: true  },
  { id: 30 , name: "Ballistik"                      , category: "versatile"  , released: true  },
  { id: 31 , name: "Bassline"                       , category: "drifter"    , released: true  },
  { id: 32 , name: "Battle Spec"                    , category: "versatile"  , released: false },
  { id: 33 , name: "Bedlam"                         , category: "drifter"    , released: true  },
  { id: 34 , name: "Big-Air Bel-Air"                , category: "titan"      , released: false },
  { id: 35 , name: "BMW M3 GT2"                     , category: "speeder"    , released: false },
  { id: 36 , name: "Bone Shaker"                    , category: "drifter"    , released: true  },
  { id: 37 , name: "Car de Asada"                   , category: "versatile"  , released: false },
  { id: 38 , name: "Celero GT"                      , category: "speeder"    , released: true  },
  { id: 39 , name: "Celero GT STH"                  , category: "speeder"    , released: true  },
  { id: 40 , name: "Chevy Silverado"                , category: "drifter"    , released: true  },
  { id: 41 , name: "Chevy Silverado STH"            , category: "titan"      , released: true  },
  { id: 42 , name: "Chicane"                        , category: "drifter"    , released: false },
  { id: 43 , name: "Corvette Stingray"              , category: "versatile"  , released: false },
  { id: 44 , name: "Custom 77 Dodge Van"            , category: "titan"      , released: true  },
  { id: 45 , name: "Custom Camaro"                  , category: "drifter"    , released: false },
  { id: 46 , name: "Custom Otto"                    , category: "versatile"  , released: true  },
  { id: 47 , name: "Custom Volkswagen Beetle"       , category: "drifter"    , released: false },
  { id: 48 , name: "Cyber Speeder"                  , category: "speeder"    , released: true  },
  { id: 49 , name: "Cyber Speeder STH"              , category: "speeder"    , released: true  },
  { id: 50 , name: "Datsun King Cab"                , category: "titan"      , released: false },
  { id: 51 , name: "Deora II"                       , category: "titan"      , released: true  },
  { id: 52 , name: "Diesel Duty"                    , category: "titan"      , released: true  },
  { id: 53 , name: "Dodge Charger RT70"             , category: "drifter"    , released: false },
  { id: 54 , name: "Dodge Viper SRT"                , category: "speeder"    , released: true  },
  { id: 55 , name: "Dodge Viper SRT STH"            , category: "drifter"    , released: true  },
  { id: 56 , name: "Donut Drifter"                  , category: "versatile"  , released: true  },
  { id: 57 , name: "Donut Drifter STH"              , category: "drifter"    , released: true  },
  { id: 58 , name: "Dragon Blaster"                 , category: "versatile"  , released: true  },
  { id: 59 , name: "Dragon Blaster STH"             , category: "titan"      , released: true  },
  { id: 60 , name: "Drift King"                     , category: "drifter"    , released: true  },
  { id: 61 , name: "Drift n Break"                  , category: "drifter"    , released: true  },
  { id: 62 , name: "Drift Rod"                      , category: "drifter"    , released: true  },
  { id: 63 , name: "Drift Tech"                     , category: "drifter"    , released: true  },
  { id: 64 , name: "Driftsta"                       , category: "drifter"    , released: true  },
  { id: 65 , name: "Duck n Roll"                    , category: "versatile"  , released: true  },
  { id: 66 , name: "Dune Crusher"                   , category: "titan"      , released: true  },
  { id: 67 , name: "El Camino"                      , category: "drifter"    , released: true  },
  { id: 68 , name: "El Camino STH"                  , category: "drifter"    , released: true  },
  { id: 69 , name: "El Segundo Coupe"               , category: "speeder"    , released: true  },
  { id: 70 , name: "F1 Racer"                       , category: "speeder"    , released: true  },
  { id: 71 , name: "Fandango"                       , category: "titan"      , released: true  },
  { id: 72 , name: "Fast Bed Hauler"                , category: "titan"      , released: true  },
  { id: 73 , name: "Fast Gassin"                    , category: "titan"      , released: true  },
  { id: 74 , name: "Feline Lucky"                   , category: "versatile"  , released: true  },
  { id: 75 , name: "Ferari 330 P4"                  , category: "speeder"    , released: false },
  { id: 76 , name: "Ferrari 12 Cilindri"            , category: "versatile"  , released: false },
  { id: 77 , name: "Ferrari 250 GTO"                , category: "drifter"    , released: false },
  { id: 78 , name: "Ferrari 312P"                   , category: "speeder"    , released: false },
  { id: 79 , name: "Ferrari 365 GTB 4"              , category: "speeder"    , released: true  },
  { id: 80 , name: "Ferrari 499P Modificata"        , category: "speeder"    , released: false },
  { id: 81 , name: "Ferrari Dino 206 GT"            , category: "versatile"  , released: false },
  { id: 82 , name: "Ferrari Enzo"                   , category: "speeder"    , released: false },
  { id: 83 , name: "Ferrari F40"                    , category: "speeder"    , released: false },
  { id: 84 , name: "Ferrari F40 Competizione"       , category: "speeder"    , released: false },
  { id: 85 , name: "Ferrari F50"                    , category: "speeder"    , released: false },
  { id: 86 , name: "Ferrari Pininfarina Battista"   , category: "speeder"    , released: false },
  { id: 87 , name: "Ferrari SF90"                   , category: "drifter"    , released: true  },
  { id: 88 , name: "Ferrari Testarossa"             , category: "drifter"    , released: false },
  { id: 89 , name: "Fiat 500"                       , category: "versatile"  , released: true  },
  { id: 90 , name: "Fiat 500 Modificato"            , category: "versatile"  , released: true  },
  { id: 91 , name: "Fiat 500 Modificato STH"        , category: "versatile"  , released: true  },
  { id: 92 , name: "Fiat 500 STH"                   , category: "versatile"  , released: true  },
  { id: 93 , name: "Flathead Fury"                  , category: "versatile"  , released: true  },
  { id: 94 , name: "Ford Bronco"                    , category: "titan"      , released: true  },
  { id: 95 , name: "Ford F-150 Lightning"           , category: "titan"      , released: true  },
  { id: 96 , name: "Ford GT Race"                   , category: "speeder"    , released: true  },
  { id: 97 , name: "Ford GT40 MkIV"                 , category: "speeder"    , released: false },
  { id: 98 , name: "Ford Mustang GT"                , category: "drifter"    , released: false },
  { id: 99 , name: "Fore Wheeler"                   , category: "versatile"  , released: true  },
  { id: 100, name: "Formula 1 2025"                 , category: "speeder"    , released: false },
  { id: 101, name: "Formula 1 2026"                 , category: "speeder"    , released: false },
  { id: 102, name: "FusionBusta"                    , category: "drifter"    , released: true  },
  { id: 103, name: "Glory Chaser"                   , category: "speeder"    , released: true  },
  { id: 104, name: "Greased Lightnin'"              , category: "speeder"    , released: true  },
  { id: 105, name: "GT-Scorcher"                    , category: "speeder"    , released: true  },
  { id: 106, name: "Hako Type D"                    , category: "drifter"    , released: false },
  { id: 107, name: "Heavy Hitcher"                  , category: "titan"      , released: false },
  { id: 108, name: "Hi-Roller II"                   , category: "versatile"  , released: true  },
  { id: 109, name: "Hi-Roller II STH"               , category: "titan"      , released: true  },
  { id: 110, name: "High Voltage"                   , category: "versatile"  , released: true  },
  { id: 111, name: "Hollowback"                     , category: "drifter"    , released: false },
  { id: 112, name: "Honda City Turbo II"            , category: "versatile"  , released: true  },
  { id: 113, name: "Honda Civic EF"                 , category: "versatile"  , released: true  },
  { id: 114, name: "Honda Civic Type R"             , category: "versatile"  , released: false },
  { id: 115, name: "Honda CRX"                      , category: "versatile"  , released: true  },
  { id: 116, name: "Honda CRX STH"                  , category: "speeder"    , released: true  },
  { id: 117, name: "Honda NSX"                      , category: "versatile"  , released: false },
  { id: 118, name: "Honda S2000"                    , category: "drifter"    , released: true  },
  { id: 119, name: "Hot Wheels High"                , category: "titan"      , released: true  },
  { id: 120, name: "Hot Wired"                      , category: "speeder"    , released: true  },
  { id: 121, name: "Hoto Roto"                      , category: "versatile"  , released: false },
  { id: 122, name: "HW Prototype 12"                , category: "versatile"  , released: true  },
  { id: 123, name: "HW Ultimate T-Rex Transporter"  , category: "titan"      , released: true  },
  { id: 124, name: "Hyperliner"                     , category: "titan"      , released: true  },
  { id: 125, name: "Iridium"                        , category: "speeder"    , released: false },
  { id: 126, name: "Jack Hammer"                    , category: "versatile"  , released: true  },
  { id: 127, name: "Kei Swap"                       , category: "titan"      , released: false },
  { id: 128, name: "Koenigsegg Gemera"              , category: "speeder"    , released: true  },
  { id: 129, name: "Koenigsegg Jesko"               , category: "speeder"    , released: false },
  { id: 130, name: "Kowloond Hypervan"              , category: "titan"      , released: true  },
  { id: 131, name: "Krazy 8's"                      , category: "speeder"    , released: false },
  { id: 132, name: "La Ferrari"                     , category: "speeder"    , released: false },
  { id: 133, name: "Lancia 037"                     , category: "versatile"  , released: false },
  { id: 134, name: "Lancia Delta"                   , category: "versatile"  , released: true  },
  { id: 135, name: "Lancia Stratos Group 5"         , category: "speeder"    , released: true  },
  { id: 136, name: "Later Crater"                   , category: "titan"      , released: true  },
  { id: 137, name: "Mad Manga"                      , category: "drifter"    , released: true  },
  { id: 138, name: "Maelstrom"                      , category: "drifter"    , released: false },
  { id: 139, name: "Max Steel"                      , category: "drifter"    , released: false },
  { id: 140, name: "Mazda 787B"                     , category: "speeder"    , released: false },
  { id: 141, name: "Mazda Miata MX5"                , category: "versatile"  , released: false },
  { id: 142, name: "Mazda RX7"                      , category: "drifter"    , released: false },
  { id: 143, name: "Mega Duty"                      , category: "titan"      , released: true  },
  { id: 144, name: "Mercedes Benz 300 SEL 68 AMG"   , category: "versatile"  , released: false },
  { id: 145, name: "Mercedes Benz 300 SL"           , category: "versatile"  , released: true  },
  { id: 146, name: "Mercedes Benz 560 SEC AMG"      , category: "drifter"    , released: true  },
  { id: 147, name: "Mercedes Benz 560 SEC AMG STH"  , category: "versatile"  , released: true  },
  { id: 148, name: "Mercedes Benz Unimog"           , category: "titan"      , released: false },
  { id: 149, name: "Mighty K"                       , category: "versatile"  , released: false },
  { id: 150, name: "Mitsubishi Eclipse"             , category: "drifter"    , released: false },
  { id: 151, name: "Mitsubishi Lancer Evo"          , category: "drifter"    , released: true  },
  { id: 152, name: "Mitsubishi Pajero"              , category: "titan"      , released: true  },
  { id: 153, name: "Mod Rod"                        , category: "drifter"    , released: true  },
  { id: 154, name: "Mod Rod STH"                    , category: "drifter"    , released: true  },
  { id: 155, name: "Mod Speeder"                    , category: "speeder"    , released: false },
  { id: 156, name: "Moto-Crossed"                   , category: "titan"      , released: true  },
  { id: 157, name: "MS-T Suzuka"                    , category: "speeder"    , released: true  },
  { id: 158, name: "Muscle Tone"                    , category: "drifter"    , released: true  },
  { id: 159, name: "Night Shifter"                  , category: "drifter"    , released: true  },
  { id: 160, name: "Nissan 35 GTR"                  , category: "speeder"    , released: true  },
  { id: 161, name: "Nissan Fairlady Z"              , category: "versatile"  , released: false },
  { id: 162, name: "Nissan Patrol Custom"           , category: "titan"      , released: true  },
  { id: 163, name: "Nissan Silvia S15"              , category: "speeder"    , released: true  },
  { id: 164, name: "Nissan Skyline GTR R32"         , category: "versatile"  , released: false },
  { id: 165, name: "Nissan Skyline GTR R34"         , category: "drifter"    , released: false },
  { id: 166, name: "Piledriver"                     , category: "versatile"  , released: true  },
  { id: 167, name: "Pony Up"                        , category: "versatile"  , released: true  },
  { id: 168, name: "Power Bomb"                     , category: "speeder"    , released: true  },
  { id: 169, name: "Power Pipes"                    , category: "versatile"  , released: true  },
  { id: 170, name: "Power Pistons"                  , category: "speeder"    , released: true  },
  { id: 171, name: "Power Rage"                     , category: "drifter"    , released: false },
  { id: 172, name: "Power Rocket"                   , category: "speeder"    , released: true  },
  { id: 173, name: "Prototype H-24"                 , category: "speeder"    , released: true  },
  { id: 174, name: "Prototype H-24 STH"             , category: "versatile"  , released: true  },
  { id: 175, name: "Punk Rod"                       , category: "speeder"    , released: false },
  { id: 176, name: "Raijin Express"                 , category: "titan"      , released: true  },
  { id: 177, name: "Raijin Express STH"             , category: "titan"      , released: true  },
  { id: 178, name: "Rally Speciale"                 , category: "versatile"  , released: true  },
  { id: 179, name: "Ram 1500"                       , category: "titan"      , released: true  },
  { id: 180, name: "Rapid Pulse"                    , category: "titan"      , released: true  },
  { id: 181, name: "Rat-ified"                      , category: "drifter"    , released: true  },
  { id: 182, name: "Ravenger ST"                    , category: "drifter"    , released: true  },
  { id: 183, name: "RD-02"                          , category: "versatile"  , released: true  },
  { id: 184, name: "RD-05"                          , category: "titan"      , released: false },
  { id: 185, name: "RD-06"                          , category: "versatile"  , released: false },
  { id: 186, name: "RD-08"                          , category: "titan"      , released: false },
  { id: 187, name: "RD-09"                          , category: "versatile"  , released: true  },
  { id: 188, name: "Reverb"                         , category: "speeder"    , released: true  },
  { id: 189, name: "Rig Heat"                       , category: "titan"      , released: true  },
  { id: 190, name: "Rig Storm"                      , category: "titan"      , released: true  },
  { id: 191, name: "Rip Rod"                        , category: "drifter"    , released: true  },
  { id: 192, name: "Rivited"                        , category: "drifter"    , released: true  },
  { id: 193, name: "Road Bandit"                    , category: "titan"      , released: true  },
  { id: 194, name: "Road Rocket"                    , category: "speeder"    , released: true  },
  { id: 195, name: "Rodger Dodger"                  , category: "drifter"    , released: true  },
  { id: 196, name: "Rodger Dodger STH"              , category: "drifter"    , released: true  },
  { id: 197, name: "Roller Toaster"                 , category: "titan"      , released: false },
  { id: 198, name: "Rollin' Thunder"                , category: "drifter"    , released: true  },
  { id: 199, name: "RRRoadster"                     , category: "speeder"    , released: true  },
  { id: 200, name: "RRRoadster STH"                 , category: "speeder"    , released: true  },
  { id: 201, name: "Runway Res-Q"                   , category: "titan"      , released: true  },
  { id: 202, name: "Sand Burner"                    , category: "titan"      , released: true  },
  { id: 203, name: "Sandivore"                      , category: "titan"      , released: false },
  { id: 204, name: "Seared Tuner"                   , category: "drifter"    , released: true  },
  { id: 205, name: "Sharkruiser"                    , category: "versatile"  , released: true  },
  { id: 206, name: "Side Draft"                     , category: "speeder"    , released: true  },
  { id: 207, name: "Slide Burn"                     , category: "drifter"    , released: true  },
  { id: 208, name: "Slingshot"                      , category: "versatile"  , released: false },
  { id: 209, name: "Sol-Aire CX4"                   , category: "speeder"    , released: false },
  { id: 210, name: "SpecTyte"                       , category: "drifter"    , released: false },
  { id: 211, name: "Speed Dozer"                    , category: "titan"      , released: true  },
  { id: 212, name: "Spine Buster"                   , category: "speeder"    , released: true  },
  { id: 213, name: "Splittin' Image 2"              , category: "versatile"  , released: true  },
  { id: 214, name: "Spoiler Sport"                  , category: "titan"      , released: true  },
  { id: 215, name: "Street Creeper"                 , category: "drifter"    , released: true  },
  { id: 216, name: "Street Creeper STH"             , category: "drifter"    , released: true  },
  { id: 217, name: "Subaru WRX"                     , category: "drifter"    , released: false },
  { id: 218, name: "Super Blitzen"                  , category: "speeder"    , released: true  },
  { id: 219, name: "Super Tuned"                    , category: "drifter"    , released: true  },
  { id: 220, name: "Surf n Turf"                    , category: "drifter"    , released: true  },
  { id: 221, name: "Surfin' School Bus"             , category: "titan"      , released: true  },
  { id: 222, name: "Sweet 16 II"                    , category: "speeder"    , released: true  },
  { id: 223, name: "Sweet 16 II STH"                , category: "speeder"    , released: true  },
  { id: 224, name: "Switchback"                     , category: "drifter"    , released: false },
  { id: 225, name: "Synkro"                         , category: "drifter"    , released: true  },
  { id: 226, name: "T-Rextroyer"                    , category: "versatile"  , released: true  },
  { id: 227, name: "T-Rextroyer STH"                , category: "titan"      , released: true  },
  { id: 228, name: "Tanknator"                      , category: "titan"      , released: true  },
  { id: 229, name: "Tanknator STH"                  , category: "titan"      , released: true  },
  { id: 230, name: "Technetium"                     , category: "versatile"  , released: true  },
  { id: 231, name: "Time Attaxi"                    , category: "drifter"    , released: true  },
  { id: 232, name: "Track Dwagon"                   , category: "drifter"    , released: false },
  { id: 233, name: "Track Manga"                    , category: "drifter"    , released: true  },
  { id: 234, name: "Tricera-Truck"                  , category: "titan"      , released: false },
  { id: 235, name: "Trouble Decker"                 , category: "titan"      , released: true  },
  { id: 236, name: "Turbine Time"                   , category: "titan"      , released: true  },
  { id: 237, name: "Twin Mill"                      , category: "versatile"  , released: true  },
  { id: 238, name: "Volkswagen Baja Bug"            , category: "titan"      , released: true  },
  { id: 239, name: "Volkswagen Drag Bus"            , category: "titan"      , released: false },
  { id: 240, name: "Volkswagen Golf GTI"            , category: "versatile"  , released: true  },
  { id: 241, name: "Volkswagen Station Wagon"       , category: "titan"      , released: true  },
  { id: 242, name: "Vulture"                        , category: "speeder"    , released: true  },
  { id: 243, name: "West Coast Flyer"               , category: "titan"      , released: false },
  { id: 244, name: "What-4-2"                       , category: "versatile"  , released: false },
  { id: 245, name: "Winning Formula"                , category: "speeder"    , released: true  }
];

const trackPool = [
  { id: 1,   name: "Dude the 3nd",                  creator: "Pato"                        },
  { id: 2,   name: "It's Payweek",                  creator: "Gunner"                      },
  { id: 3,   name: "King of the Hill",              creator: "Gore"                        },
  { id: 4,   name: "Gluten Freeway",                creator: "Bread"                       },
  { id: 5,   name: "SG Many Teeth",                 creator: "Swole"                       },
  { id: 6,   name: "HW 36 Set",                     creator: "TRD"                         },
  { id: 7,   name: "S- Nostalgia 02",               creator: "Swampee"                     },
  { id: 8,   name: "Biy Biy Bikes",                 creator: "Biyzor"                      },
  { id: 9,   name: "Orthodox Sigma",                creator: "Fidestic"                    },
  { id: 10,  name: "Mickey",                        creator: "Thrashinator"                },
];

const iconPool = [
  "froggy_babyblue.png",
  "froggy_blue.png",
  "froggy_camo.png",
  "froggy_car.png",
  "froggy_cheese.png",
  "froggy_cleopatra.png",
  "froggy_errorscreen.png",
  "froggy_evil.png",
  "froggy_junkyard.png",
  "froggy_metalpipes.png",
  "froggy_monstertruck.png",
  "froggy_muddy.png",
  "froggy_pinky.png",
  "froggy_racecarred.png",
  "froggy_racecarwhite.png",
  "froggy_rainbow.png",
  "froggy_rusty.png",
  "froggy_shades.png",
  "froggy_slime.png",
  "froggy_taxi.png",
  "froggy_teal.png",
  "froggy_trooper.png",
];