const carPool = [
  { id: 1,   name: "16 Angels",                     category: "drifter",   released: true  },
  { id: 2,   name: "16 Angels STH",                 category: "drifter",   released: true  },
  { id: 3,   name: "2001 Mini Cooper",              category: "drifter",   released: false },
  { id: 4,   name: "2020 Corvette",                 category: "drifter",   released: true  },
  { id: 5,   name: "2020 Corvette STH",             category: "drifter",   released: true  },
  { id: 6,   name: "24 Ours",                       category: "drifter",   released: true  },
  { id: 7,   name: "24 Seven",                      category: "drifter",   released: true  },
  { id: 8,   name: "40 Somethin",                   category: "drifter",   released: true  },
  { id: 9,   name: "5 Alarm",                       category: "drifter",   released: true  },
  { id: 10,  name: "91 BMW M3",                     category: "drifter",   released: false },
  { id: 11,  name: "91 Mazda Miata MX5",            category: "drifter",   released: true  },
  { id: 12,  name: "91 Mazda Miata MX5 STH",        category: "drifter",   released: true  },
  { id: 13,  name: "91 Mercedes Benz G-Class",      category: "drifter",   released: false },
  { id: 14,  name: "98 Subaru Impreza",             category: "drifter",   released: false },
  { id: 15,  name: "Aeroflash",                     category: "drifter",   released: false },
  { id: 16,  name: "Alfa Romeo 155 V6",             category: "drifter",   released: true  },
  { id: 17,  name: "Alfa Romeo Giulia",             category: "drifter",   released: false },
  { id: 18,  name: "Anthracite",                    category: "drifter",   released: true  },
  { id: 19,  name: "Aristo Rat",                    category: "drifter",   released: true  },
  { id: 20,  name: "Aston Martin DBS",              category: "drifter",   released: false },
  { id: 21,  name: "Aston Martin Vulcan",           category: "drifter",   released: true  },
  { id: 22,  name: "Audi R8 LMS",                   category: "drifter",   released: false },
  { id: 23,  name: "Audi RS5 Coupe",                category: "drifter",   released: true  },
  { id: 24,  name: "Audi Sport Quattro",            category: "drifter",   released: true  },
  { id: 25,  name: "Backdraft",                     category: "drifter",   released: true  },
  { id: 26,  name: "Bad to the Blade",              category: "drifter",   released: true  },
  { id: 27,  name: "Baja Bison",                    category: "drifter",   released: true  },
  { id: 28,  name: "Baja Bone Shaker",              category: "drifter",   released: false },
  { id: 29,  name: "Baja Truck",                    category: "drifter",   released: true  },
  { id: 30,  name: "Ballistik",                     category: "drifter",   released: true  },
  { id: 31,  name: "Bassline",                      category: "drifter",   released: true  },
  { id: 32,  name: "Battle Spec",                   category: "drifter",   released: false },
  { id: 33,  name: "Bedlam",                        category: "drifter",   released: true  },
  { id: 34,  name: "Big-Air Bel-Air",               category: "drifter",   released: false },
  { id: 35,  name: "BMW M3 GT2",                    category: "drifter",   released: false },
  { id: 36,  name: "Bone Shaker",                   category: "drifter",   released: true  },
  { id: 37,  name: "Car de Asada",                  category: "drifter",   released: false },
  { id: 38,  name: "Celero GT",                     category: "drifter",   released: true  },
  { id: 39,  name: "Celero GT STH",                 category: "drifter",   released: true  },
  { id: 40,  name: "Chevy Silverado",               category: "drifter",   released: true  },
  { id: 41,  name: "Chevy Silverado STH",           category: "drifter",   released: true  },
  { id: 42,  name: "Chicane",                       category: "drifter",   released: false },
  { id: 43,  name: "Corvette C8",                   category: "drifter",   released: false },
  { id: 44,  name: "Custom 77 Dodge Van",           category: "drifter",   released: true  },
  { id: 45,  name: "Custom Camaro",                 category: "drifter",   released: false },
  { id: 46,  name: "Custom Otto",                   category: "drifter",   released: true  },
  { id: 47,  name: "Custom Volkswagen Beetle",      category: "drifter",   released: false },
  { id: 48,  name: "Cyber Speeder",                 category: "drifter",   released: true  },
  { id: 49,  name: "Cyber Speeder STH",             category: "drifter",   released: true  },
  { id: 50,  name: "Datsun King Cab",               category: "drifter",   released: false },
  { id: 51,  name: "Deora II",                      category: "drifter",   released: true  },
  { id: 52,  name: "Diesel Duty",                   category: "drifter",   released: true  },
  { id: 53,  name: "Dodge Charger RT70",            category: "drifter",   released: false },
  { id: 54,  name: "Dodge Viper SRT",               category: "drifter",   released: true  },
  { id: 55,  name: "Dodge Viper SRT STH",           category: "drifter",   released: true  },
  { id: 56,  name: "Donut Drifter",                 category: "drifter",   released: true  },
  { id: 57,  name: "Donut Drifter STH",             category: "drifter",   released: true  },
  { id: 58,  name: "Dragon Blaster",                category: "titan",     released: true  },
  { id: 59,  name: "Dragon Blaster STH",            category: "titan",     released: true  },
  { id: 60,  name: "Drift King",                    category: "drifter",   released: true  },
  { id: 61,  name: "Drift n Break",                 category: "drifter",   released: true  },
  { id: 62,  name: "Drift Rod",                     category: "drifter",   released: true  },
  { id: 63,  name: "Drift Tech",                    category: "drifter",   released: true  },
  { id: 64,  name: "Driftsta",                      category: "drifter",   released: true  },
  { id: 65,  name: "Duck n Roll",                   category: "drifter",   released: true  },
  { id: 66,  name: "Dune Crusher",                  category: "drifter",   released: true  },
  { id: 67,  name: "El Camino",                     category: "drifter",   released: true  },
  { id: 68,  name: "El Camino STH",                 category: "drifter",   released: true  },
  { id: 69,  name: "El Segundo Coupe",              category: "drifter",   released: true  },
  { id: 70,  name: "F1 Racer",                      category: "drifter",   released: true  },
  { id: 71,  name: "Fandango",                      category: "drifter",   released: true  },
  { id: 72,  name: "Fast Bed Hauler",               category: "drifter",   released: true  },
  { id: 73,  name: "Fast Gassin",                   category: "speeder",   released: true  },
  { id: 74,  name: "Feline Lucky",                  category: "drifter",   released: true  },
  { id: 75,  name: "Ferari 330 P4",                 category: "drifter",   released: false },
  { id: 76,  name: "Ferrari 12 Cilindri",           category: "drifter",   released: false },
  { id: 77,  name: "Ferrari 250 GTO",               category: "drifter",   released: false },
  { id: 78,  name: "Ferrari 312P",                  category: "drifter",   released: false },
  { id: 79,  name: "Ferrari 365 GTB 4",             category: "drifter",   released: true  },
  { id: 80,  name: "Ferrari Dino 206 GT",           category: "drifter",   released: false },
  { id: 81,  name: "Ferrari Enzo",                  category: "drifter",   released: false },
  { id: 82,  name: "Ferrari F40",                   category: "drifter",   released: false },
  { id: 83,  name: "Ferrari F40 Competizione",      category: "drifter",   released: false },
  { id: 84,  name: "Ferrari F50",                   category: "drifter",   released: false },
  { id: 85,  name: "Ferrari Pininfarina Battista",  category: "drifter",   released: false },
  { id: 86,  name: "Ferrari SF90",                  category: "drifter",   released: true  },
  { id: 87,  name: "Ferrari Testarossa",            category: "drifter",   released: false },
  { id: 88,  name: "Fiat 500",                      category: "drifter",   released: true  },
  { id: 89,  name: "Fiat 500 Modificato",           category: "drifter",   released: true  },
  { id: 90,  name: "Fiat 500 Modificato STH",       category: "drifter",   released: true  },
  { id: 91,  name: "Fiat 500 STH",                  category: "drifter",   released: true  },
  { id: 92,  name: "Flathead Fury",                 category: "drifter",   released: true  },
  { id: 93,  name: "Ford Bronco",                   category: "drifter",   released: true  },
  { id: 94,  name: "Ford F-150 Lightning",          category: "drifter",   released: true  },
  { id: 95,  name: "Ford GT Race",                  category: "drifter",   released: true  },
  { id: 96,  name: "Ford GT40 MkIV",                category: "drifter",   released: false },
  { id: 97,  name: "Ford Mustang GT",               category: "drifter",   released: false },
  { id: 98,  name: "Fore Wheeler",                  category: "drifter",   released: true  },
  { id: 99,  name: "Formula 1 2025",                category: "drifter",   released: false },
  { id: 100, name: "Formula 1 2026",                category: "drifter",   released: false },
  { id: 101, name: "FusionBusta",                   category: "drifter",   released: true  },
  { id: 102, name: "Glory Chaser",                  category: "drifter",   released: true  },
  { id: 103, name: "Greased Lightnin'",             category: "drifter",   released: true  },
  { id: 104, name: "GT-Scorcher",                   category: "drifter",   released: true  },
  { id: 105, name: "Hako Type D",                   category: "drifter",   released: false },
  { id: 106, name: "Heavy Hitcher",                 category: "drifter",   released: false },
  { id: 107, name: "Hi-Roller II",                  category: "drifter",   released: true  },
  { id: 108, name: "Hi-Roller II STH",              category: "drifter",   released: true  },
  { id: 109, name: "High Voltage",                  category: "drifter",   released: true  },
  { id: 110, name: "Hollowback",                    category: "drifter",   released: false },
  { id: 111, name: "Honda City Turbo II",           category: "drifter",   released: true  },
  { id: 112, name: "Honda Civic EF",                category: "drifter",   released: true  },
  { id: 113, name: "Honda Civic Type R",            category: "drifter",   released: false },
  { id: 114, name: "Honda CRX",                     category: "drifter",   released: true  },
  { id: 115, name: "Honda CRX STH",                 category: "drifter",   released: true  },
  { id: 116, name: "Honda NSX",                     category: "drifter",   released: false },
  { id: 117, name: "Honda S2000",                   category: "drifter",   released: true  },
  { id: 118, name: "Hot Wheels High",               category: "drifter",   released: true  },
  { id: 119, name: "Hot Wired",                     category: "drifter",   released: true  },
  { id: 120, name: "Hoto Roto",                     category: "drifter",   released: false },
  { id: 121, name: "HW Prototype 12",               category: "drifter",   released: true  },
  { id: 122, name: "HW Ultimate T-Rex Transporter", category: "drifter",   released: true  },
  { id: 123, name: "Hyperliner",                    category: "drifter",   released: true  },
  { id: 124, name: "Iridium",                       category: "drifter",   released: false },
  { id: 125, name: "Jack Hammer",                   category: "drifter",   released: true  },
  { id: 126, name: "Kei Swap",                      category: "drifter",   released: false },
  { id: 127, name: "Koenigsegg Gemera",             category: "drifter",   released: true  },
  { id: 128, name: "Koenigsegg Jesko",              category: "drifter",   released: false },
  { id: 129, name: "Kowloond Hypervan",             category: "drifter",   released: true  },
  { id: 130, name: "Krazy 8's",                     category: "drifter",   released: false },
  { id: 131, name: "La Ferrari",                    category: "drifter",   released: false },
  { id: 132, name: "Lancia 037",                    category: "drifter",   released: false },
  { id: 133, name: "Lancia Delta",                  category: "drifter",   released: true  },
  { id: 134, name: "Lancia Stratos Group 5",        category: "drifter",   released: true  },
  { id: 135, name: "Later Crater",                  category: "drifter",   released: true  },
  { id: 136, name: "Mad Manga",                     category: "drifter",   released: true  },
  { id: 137, name: "Maelstrom",                     category: "drifter",   released: false },
  { id: 138, name: "Max Steel",                     category: "drifter",   released: false },
  { id: 139, name: "Mazda 787B",                    category: "drifter",   released: false },
  { id: 140, name: "Mazda Miata MX5",               category: "drifter",   released: false },
  { id: 141, name: "Mazda RX7",                     category: "drifter",   released: false },
  { id: 142, name: "Mega Duty",                     category: "drifter",   released: true  },
  { id: 143, name: "Mercedes Benz 300 SEL 68 AMG",  category: "drifter",   released: false },
  { id: 144, name: "Mercedes Benz 300 SL",          category: "drifter",   released: true  },
  { id: 145, name: "Mercedes Benz 560 SEC AMG",     category: "drifter",   released: true  },
  { id: 146, name: "Mercedes Benz 560 SEC AMG STH", category: "drifter",   released: true  },
  { id: 147, name: "Mercedes Benz Unimog",          category: "drifter",   released: false },
  { id: 148, name: "Mighty K",                      category: "drifter",   released: false },
  { id: 149, name: "Mitsubishi Eclipse",            category: "drifter",   released: false },
  { id: 150, name: "Mitsubishi Lancer Evo",         category: "drifter",   released: true  },
  { id: 151, name: "Mitsubishi Pajero",             category: "drifter",   released: true  },
  { id: 152, name: "Mod Rod",                       category: "drifter",   released: true  },
  { id: 153, name: "Mod Rod STH",                   category: "drifter",   released: true  },
  { id: 154, name: "Mod Speeder",                   category: "drifter",   released: false },
  { id: 155, name: "Moto-Crossed",                  category: "drifter",   released: true  },
  { id: 156, name: "MS-T Suzuka",                   category: "drifter",   released: true  },
  { id: 157, name: "Muscle Tone",                   category: "drifter",   released: true  },
  { id: 158, name: "Night Shifter",                 category: "titan",     released: true  },
  { id: 159, name: "Nissan 35 GTR",                 category: "drifter",   released: true  },
  { id: 160, name: "Nissan Fairlady Z",             category: "drifter",   released: false },
  { id: 161, name: "Nissan Patrol Custom",          category: "drifter",   released: true  },
  { id: 162, name: "Nissan Silvia S15",             category: "drifter",   released: true  },
  { id: 163, name: "Nissan Skyline GTR R32",        category: "drifter",   released: false },
  { id: 164, name: "Nissan Skyline GTR R34",        category: "drifter",   released: false },
  { id: 165, name: "Piledriver",                    category: "drifter",   released: true  },
  { id: 166, name: "Pony Up",                       category: "drifter",   released: true  },
  { id: 167, name: "Power Bomb",                    category: "drifter",   released: true  },
  { id: 168, name: "Power Pipes",                   category: "drifter",   released: true  },
  { id: 169, name: "Power Pistons",                 category: "drifter",   released: true  },
  { id: 170, name: "Power Rage",                    category: "drifter",   released: false },
  { id: 171, name: "Power Rocket",                  category: "speeder",   released: true  },
  { id: 172, name: "Prototype H-24",                category: "drifter",   released: true  },
  { id: 173, name: "Prototype H-24 STH",            category: "drifter",   released: true  },
  { id: 174, name: "Punk Rod",                      category: "drifter",   released: false },
  { id: 175, name: "Raijin Express",                category: "drifter",   released: true  },
  { id: 176, name: "Raijin Express STH",            category: "drifter",   released: true  },
  { id: 177, name: "Rally Speciale",                category: "drifter",   released: true  },
  { id: 178, name: "Ram 1500",                      category: "drifter",   released: true  },
  { id: 179, name: "Rapid Pulse",                   category: "drifter",   released: true  },
  { id: 180, name: "Rat-ified",                     category: "drifter",   released: true  },
  { id: 181, name: "Ravenger ST",                   category: "drifter",   released: true  },
  { id: 182, name: "RD-02",                         category: "drifter",   released: true  },
  { id: 183, name: "RD-05",                         category: "drifter",   released: false },
  { id: 184, name: "RD-06",                         category: "drifter",   released: false },
  { id: 185, name: "RD-08",                         category: "drifter",   released: false },
  { id: 186, name: "RD-09",                         category: "drifter",   released: true  },
  { id: 187, name: "Reverb",                        category: "drifter",   released: true  },
  { id: 188, name: "Rig Heat",                      category: "drifter",   released: true  },
  { id: 189, name: "Rig Storm",                     category: "drifter",   released: true  },
  { id: 190, name: "Rip Rod",                       category: "versatile", released: true  },
  { id: 191, name: "Rivited",                       category: "drifter",   released: true  },
  { id: 192, name: "Road Bandit",                   category: "drifter",   released: true  },
  { id: 193, name: "Road Rocket",                   category: "drifter",   released: true  },
  { id: 194, name: "Rodger Dodger",                 category: "versatile", released: true  },
  { id: 195, name: "Rodger Dodger STH",             category: "versatile", released: true  },
  { id: 196, name: "Roller Toaster",                category: "drifter",   released: false },
  { id: 197, name: "Rollin' Thunder",               category: "drifter",   released: true  },
  { id: 198, name: "RRRoadster",                    category: "drifter",   released: true  },
  { id: 199, name: "RRRoadster STH",                category: "drifter",   released: true  },
  { id: 200, name: "Runway Res-Q",                  category: "drifter",   released: true  },
  { id: 201, name: "Sand Burner",                   category: "drifter",   released: true  },
  { id: 202, name: "Sandivore",                     category: "drifter",   released: false },
  { id: 203, name: "Seared Tuner",                  category: "drifter",   released: true  },
  { id: 204, name: "Sharkruiser",                   category: "drifter",   released: true  },
  { id: 205, name: "Side Draft",                    category: "drifter",   released: true  },
  { id: 206, name: "Slide Burn",                    category: "drifter",   released: true  },
  { id: 207, name: "Slingshot",                     category: "drifter",   released: false },
  { id: 208, name: "Sol-Aire CX4",                  category: "drifter",   released: false },
  { id: 209, name: "SpecTyte",                      category: "drifter",   released: false },
  { id: 210, name: "Speed Dozer",                   category: "drifter",   released: true  },
  { id: 211, name: "Spine Buster",                  category: "drifter",   released: true  },
  { id: 212, name: "Splittin' Image 2",             category: "drifter",   released: true  },
  { id: 213, name: "Spoiler Sport",                 category: "drifter",   released: true  },
  { id: 214, name: "Street Creeper",                category: "drifter",   released: true  },
  { id: 215, name: "Street Creeper STH",            category: "drifter",   released: true  },
  { id: 216, name: "Subaru WRX",                    category: "drifter",   released: false },
  { id: 217, name: "Super Blitzen",                 category: "drifter",   released: true  },
  { id: 218, name: "Super Tuned",                   category: "drifter",   released: true  },
  { id: 219, name: "Surf n Turf",                   category: "drifter",   released: true  },
  { id: 220, name: "Surfin' School Bus",            category: "drifter",   released: true  },
  { id: 221, name: "Sweet 16 II",                   category: "drifter",   released: true  },
  { id: 222, name: "Sweet 16 II STH",               category: "drifter",   released: true  },
  { id: 223, name: "Switchback",                    category: "drifter",   released: false },
  { id: 224, name: "Synkro",                        category: "drifter",   released: true  },
  { id: 225, name: "T-Rextroyer",                   category: "drifter",   released: true  },
  { id: 226, name: "T-Rextroyer STH",               category: "drifter",   released: true  },
  { id: 227, name: "Tanknator",                     category: "drifter",   released: true  },
  { id: 228, name: "Tanknator STH",                 category: "drifter",   released: true  },
  { id: 229, name: "Technetium",                    category: "drifter",   released: true  },
  { id: 230, name: "Time Attaxi",                   category: "drifter",   released: true  },
  { id: 231, name: "Track Dwagon",                  category: "drifter",   released: false },
  { id: 232, name: "Track Manga",                   category: "drifter",   released: true  },
  { id: 233, name: "Tricera-Truck",                 category: "drifter",   released: false },
  { id: 234, name: "Trouble Decker",                category: "drifter",   released: true  },
  { id: 235, name: "Turbine Time",                  category: "drifter",   released: true  },
  { id: 236, name: "Twin Mill",                     category: "drifter",   released: true  },
  { id: 237, name: "Volkswagen Baja Bug",           category: "drifter",   released: true  },
  { id: 238, name: "Volkswagen Drag Bus",           category: "drifter",   released: false },
  { id: 239, name: "Volkswagen Golf GTI",           category: "drifter",   released: true  },
  { id: 240, name: "Volkswagen Station Wagon",      category: "drifter",   released: true  },
  { id: 241, name: "Vulture",                       category: "drifter",   released: true  },
  { id: 242, name: "West Coast Flyer",              category: "drifter",   released: false },
  { id: 243, name: "What-4-2",                      category: "drifter",   released: false },
  { id: 244, name: "Winning Formula",               category: "drifter",   released: true  },
  { id: 245, name: "Ferrari 499P Modificata",       category: "drifter",   released: false }
];

const trackPool = [
  { id: 1,   name: "Dude the 3nd",                  creator: "Pato"                        },
  { id: 2,   name: "It's Payweek",                  creator: "Gunner"                      },
  { id: 3,   name: "King of the Hill",              creator: "Gore"                        },
  { id: 4,   name: "Gluten Freeway",                creator: "Bread"                       },
  { id: 5,   name: "SG Many Teeth",                 creator: "Swole"                       },
  { id: 6,   name: "HW 36 Set",                     creator: "TRD"                         },
  { id: 7,   name: "S- Nostalgia 02",               creator: "Swampee"                     },
  { id: 8,   name: "Biy Biy Bikes",                 creator: "Biyzor"                      },
  { id: 9,   name: "Orthodox Sigma",                creator: "Fidestic"                    },
  { id: 10,  name: "Mickey",                        creator: "Thrashinator"                },
];

const iconPool = [
  "froggy_babyblue.png",
  "froggy_blue.png",
  "froggy_camo.png",
  "froggy_car.png",
  "froggy_cheese.png",
  "froggy_cleopatra.png",
  "froggy_errorscreen.png",
  "froggy_evil.png",
  "froggy_junkyard.png",
  "froggy_metalpipes.png",
  "froggy_monstertruck.png",
  "froggy_muddy.png",
  "froggy_pinky.png",
  "froggy_racecarred.png",
  "froggy_racecarwhite.png",
  "froggy_rainbow.png",
  "froggy_rusty.png",
  "froggy_shades.png",
  "froggy_slime.png",
  "froggy_taxi.png",
  "froggy_teal.png",
  "froggy_trooper.png",
];