// data-game2.js
// Car + track pool for the PREVIOUS game. Kept entirely separate from
// data.js (the current game's pool) on purpose -- different games,
// different car classes, never mixed together.
//
// Game 2 cars carry real stats (top speed, boost, weight, etc.) scraped
// from the community spreadsheet; Game 1 cars don't have stats, which is
// expected -- the UI only shows a stats block when `stats` is present.
//
// Everything below (each creator's track object, like `biyzor` or `pato`)
// lives INSIDE this IIFE on purpose, not as top-level consts -- data.js
// (Game 1) likely has its own per-creator variables with the same names
// (same community making tracks for both games), and two global `const
// biyzor`s from two different files WILL collide ("already declared").
// Only `game2Cars` and `trackCollections` escape to the global scope.

const { game2Cars, trackCollections: game2TrackCollections } = (function () {
  const game2Cars = [
    { id: 1,   name: "RD-02",                                       category: "Balanced",      stats: { topSpeed: 98.5, boostAmount: 3, boostType: "Charge", boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: true  } },
    { id: 2,   name: "1971 El Camino STH",                          category: "Drifter",       stats: { topSpeed: 97.6, boostAmount: 3, boostType: "Bar",    boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 3,   name: "GT-Scorcher",                                 category: "Balanced",      stats: { topSpeed: 97.5, boostAmount: 3, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 4,   name: "Ducati 1199 Panigale [Bike]",                 category: "Bike",          stats: { topSpeed: 97.0, boostAmount: 4, boostType: "Charge", boostPower: 131.5, driftBoostGain: 0.42, passiveBoostGain: 0.07, baseWeight: 400,  weightModifier: null,    banned: true  } },
    { id: 5,   name: "2010 Aston Martin DBS",                       category: "Balanced",      stats: { topSpeed: 97.0, boostAmount: 3, boostType: "Charge", boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 6,   name: "Fast Gassin'",                                category: "Heavy",         stats: { topSpeed: 96.2, boostAmount: 4, boostType: "Bar",    boostPower: 49.8,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 2350, weightModifier: null,    banned: false } },
    { id: 7,   name: "Bad Bagger [Bike]",                           category: "Bike",          stats: { topSpeed: 95.9, boostAmount: 3, boostType: "Charge", boostPower: 131.5, driftBoostGain: 0.42, passiveBoostGain: 0.07, baseWeight: 400,  weightModifier: null,    banned: false } },
    { id: 8,   name: "BMW R nineT Racer [Bike]",                    category: "Bike",          stats: { topSpeed: 95.9, boostAmount: 3, boostType: "Bar",    boostPower: 131.5, driftBoostGain: 0.42, passiveBoostGain: 0.07, baseWeight: 400,  weightModifier: null,    banned: true  } },
    { id: 9,   name: "Power Rage",                                  category: "Balanced",      stats: { topSpeed: 95.9, boostAmount: 3, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 10,  name: "Supercharged",                                category: "Balanced",      stats: { topSpeed: 95.9, boostAmount: 3, boostType: "Charge", boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 11,  name: "Street Stealth [Bike]",                       category: "Bike",          stats: { topSpeed: 95.8, boostAmount: 3, boostType: "Charge", boostPower: 131.5, driftBoostGain: 0.42, passiveBoostGain: 0.07, baseWeight: 400,  weightModifier: null,    banned: true  } },
    { id: 12,  name: "Street Wiener",                               category: "Balanced",      stats: { topSpeed: 95.8, boostAmount: 4, boostType: "Charge", boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 13,  name: "24 Ours",                                     category: "Rocket",        stats: { topSpeed: 95.7, boostAmount: 3, boostType: "Charge", boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 14,  name: "DAVancenator",                                category: "Rocket",        stats: { topSpeed: 95.7, boostAmount: 5, boostType: "Bar",    boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: true  } },
    { id: 15,  name: "Sol-Aire CX4",                                category: "Rocket",        stats: { topSpeed: 95.7, boostAmount: 3, boostType: "Bar",    boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 16,  name: "Veloci-Racer",                                category: "Rocket",        stats: { topSpeed: 95.7, boostAmount: 3, boostType: "Charge", boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 17,  name: "2020 Koenigsegg Jesko",                       category: "Balanced",      stats: { topSpeed: 95.7, boostAmount: 4, boostType: "Charge", boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 18,  name: "Exotique",                                    category: "Balanced",      stats: { topSpeed: 95.7, boostAmount: 4, boostType: "Charge", boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 19,  name: "Rollin' Thunder",                             category: "Off-Road",      stats: { topSpeed: 95.6, boostAmount: 4, boostType: "Charge", boostPower: 61.0,  driftBoostGain: 0.58, passiveBoostGain: 0.15, baseWeight: 1900, weightModifier: null,    banned: false } },
    { id: 20,  name: "Audi R8 Spyder",                              category: "Balanced",      stats: { topSpeed: 95.6, boostAmount: 3, boostType: "Charge", boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 21,  name: "Car-de-Asada",                                category: "Balanced",      stats: { topSpeed: 95.6, boostAmount: 4, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 22,  name: "Iridium",                                     category: "Balanced",      stats: { topSpeed: 95.6, boostAmount: 4, boostType: "Charge", boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 23,  name: "Duck N' Roll",                                category: "Heavy",         stats: { topSpeed: 95.6, boostAmount: 4, boostType: "Charge", boostPower: 49.8,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 2350, weightModifier: null,    banned: false } },
    { id: 24,  name: "Baja Truck",                                  category: "Off-Road",      stats: { topSpeed: 95.4, boostAmount: 5, boostType: "Bar",    boostPower: 61.0,  driftBoostGain: 0.58, passiveBoostGain: 0.15, baseWeight: 1900, weightModifier: null,    banned: false } },
    { id: 25,  name: "Track Manga",                                 category: "Rocket",        stats: { topSpeed: 95.4, boostAmount: 2, boostType: "Charge", boostPower: 86.3,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1125, weightModifier: "x0.9",  banned: false } },
    { id: 26,  name: "Twin Mill",                                   category: "Balanced",      stats: { topSpeed: 95.4, boostAmount: 3, boostType: "Charge", boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 27,  name: "Ducati Diavel [Bike]",                        category: "Bike",          stats: { topSpeed: 95.3, boostAmount: 3, boostType: "Charge", boostPower: 131.5, driftBoostGain: 0.42, passiveBoostGain: 0.07, baseWeight: 400,  weightModifier: null,    banned: true  } },
    { id: 28,  name: "Piledriver",                                  category: "Off-Road",      stats: { topSpeed: 95.3, boostAmount: 4, boostType: "Bar",    boostPower: 61.0,  driftBoostGain: 0.58, passiveBoostGain: 0.15, baseWeight: 1900, weightModifier: null,    banned: false } },
    { id: 29,  name: "Glory Chaser",                                category: "Rocket",        stats: { topSpeed: 95.3, boostAmount: 4, boostType: "Charge", boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 30,  name: "Lancia Stratos Group 5",                      category: "Rally",         stats: { topSpeed: 95.3, boostAmount: 5, boostType: "Charge", boostPower: 69.6,  driftBoostGain: 0.58, passiveBoostGain: 0.15, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 31,  name: "Roadster Bite",                               category: "Balanced",      stats: { topSpeed: 95.3, boostAmount: 3, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 32,  name: "Power Pro",                                   category: "Balanced",      stats: { topSpeed: 95.3, boostAmount: 3, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 33,  name: "Snoopy",                                      category: "Swift",         stats: { topSpeed: 95.2, boostAmount: 3, boostType: "Charge", boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: true  } },
    { id: 34,  name: "Way 2 Fast",                                  category: "Drifter",       stats: { topSpeed: 95.1, boostAmount: 3, boostType: "Bar",    boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 35,  name: "2016 Bugatti Chiron",                         category: "Rocket",        stats: { topSpeed: 95.1, boostAmount: 4, boostType: "Bar",    boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 36,  name: "El Superfasto",                               category: "Balanced",      stats: { topSpeed: 95.1, boostAmount: 2, boostType: "Charge", boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 37,  name: "Twin Mill STH",                               category: "Balanced",      stats: { topSpeed: 95.1, boostAmount: 4, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 38,  name: "2018 Honda Civic Type R",                     category: "Swift",         stats: { topSpeed: 95.1, boostAmount: 5, boostType: "Charge", boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: true  } },
    { id: 39,  name: "MS-T Suzuka",                                 category: "Rocket",        stats: { topSpeed: 95.0, boostAmount: 3, boostType: "Bar",    boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 40,  name: "Speed Slayer",                                category: "Rocket",        stats: { topSpeed: 95.0, boostAmount: 4, boostType: "Bar",    boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 41,  name: "RD-09",                                       category: "Balanced",      stats: { topSpeed: 95.0, boostAmount: 3, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 42,  name: "F1 Racer",                                    category: "Rocket",        stats: { topSpeed: 94.9, boostAmount: 5, boostType: "Charge", boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 43,  name: "Sling Shot",                                  category: "Rocket",        stats: { topSpeed: 94.9, boostAmount: 3, boostType: "Charge", boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 44,  name: "Winning Formula",                             category: "Rocket",        stats: { topSpeed: 94.9, boostAmount: 3, boostType: "Charge", boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 45,  name: "Canyon Carver [Bike]",                        category: "Bike",          stats: { topSpeed: 94.8, boostAmount: 3, boostType: "Charge", boostPower: 131.5, driftBoostGain: 0.42, passiveBoostGain: 0.07, baseWeight: 400,  weightModifier: null,    banned: false } },
    { id: 46,  name: "Ducati Desert X [Bike]",                      category: "Bike",          stats: { topSpeed: 94.8, boostAmount: 3, boostType: "Charge", boostPower: 131.5, driftBoostGain: 0.42, passiveBoostGain: 0.07, baseWeight: 400,  weightModifier: null,    banned: true  } },
    { id: 47,  name: "Test Subject [MT]",                           category: "Monster Truck", stats: { topSpeed: 94.8, boostAmount: 4, boostType: "Charge", boostPower: 42.9,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 3000, weightModifier: null,    banned: false } },
    { id: 48,  name: "Hot Wired",                                   category: "Drifter",       stats: { topSpeed: 94.8, boostAmount: 3, boostType: "Charge", boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 49,  name: "Power Sander [ATV]",                          category: "Quad",          stats: { topSpeed: 94.8, boostAmount: 5, boostType: "Bar",    boostPower: 113.2, driftBoostGain: 0.58, passiveBoostGain: 0.15, baseWeight: 800,  weightModifier: null,    banned: true  } },
    { id: 50,  name: "Group C Fantasy",                             category: "Rocket",        stats: { topSpeed: 94.8, boostAmount: 3, boostType: "Charge", boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 51,  name: "LB-Silhouette WORKS GT Nissan 35GT-RR VER.2", category: "Rocket",        stats: { topSpeed: 94.8, boostAmount: 3, boostType: "Charge", boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 52,  name: "1971 Mercedes-Benz 300 SEL 6.8 AMG",          category: "Balanced",      stats: { topSpeed: 94.8, boostAmount: 4, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 53,  name: "BMW M5 (F&F)",                                category: "Swift",         stats: { topSpeed: 94.8, boostAmount: 4, boostType: "Charge", boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: true  } },
    { id: 54,  name: "Diesel Duty",                                 category: "Off-Road",      stats: { topSpeed: 94.7, boostAmount: 6, boostType: "Bar",    boostPower: 61.0,  driftBoostGain: 0.58, passiveBoostGain: 0.15, baseWeight: 1900, weightModifier: null,    banned: false } },
    { id: 55,  name: "2016 Mercedes-AMG GT3",                       category: "Rocket",        stats: { topSpeed: 94.7, boostAmount: 3, boostType: "Charge", boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 56,  name: "Prototype H-24 TH",                           category: "Rocket",        stats: { topSpeed: 94.7, boostAmount: 3, boostType: "Charge", boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 57,  name: "Cosmic Coupe",                                category: "Balanced",      stats: { topSpeed: 94.7, boostAmount: 3, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 58,  name: "Nissan Skyline GT-R R32",                     category: "Balanced",      stats: { topSpeed: 94.7, boostAmount: 4, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 59,  name: "Twin Mill Unleashed Edition",                 category: "Balanced",      stats: { topSpeed: 94.7, boostAmount: 4, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 60,  name: "Honda S2000",                                 category: "Swift",         stats: { topSpeed: 94.7, boostAmount: 4, boostType: "Charge", boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: true  } },
    { id: 61,  name: "SpecTyte",                                    category: "Off-Road",      stats: { topSpeed: 94.6, boostAmount: 5, boostType: "Bar",    boostPower: 61.0,  driftBoostGain: 0.58, passiveBoostGain: 0.15, baseWeight: 1900, weightModifier: null,    banned: false } },
    { id: 62,  name: "Alfa Romeo 155 V6 TI",                        category: "Rocket",        stats: { topSpeed: 94.6, boostAmount: 3, boostType: "Charge", boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 63,  name: "Lancia Delta HF Integrale",                   category: "Rally",         stats: { topSpeed: 94.6, boostAmount: 4, boostType: "Charge", boostPower: 69.6,  driftBoostGain: 0.58, passiveBoostGain: 0.15, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 64,  name: "Nissan Skyline GT-R R34 (F&F)",               category: "Swift",         stats: { topSpeed: 94.6, boostAmount: 4, boostType: "Charge", boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: true  } },
    { id: 65,  name: "1970 Dodge Charger R/T (F&F)",                category: "Drifter",       stats: { topSpeed: 94.5, boostAmount: 4, boostType: "Charge", boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: true  } },
    { id: 66,  name: "Bone Shaker",                                 category: "Drifter",       stats: { topSpeed: 94.5, boostAmount: 3, boostType: "Charge", boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 67,  name: "Drift King",                                  category: "Drifter",       stats: { topSpeed: 94.5, boostAmount: 5, boostType: "Bar",    boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 68,  name: "Dragon Blaster TH",                           category: "Balanced",      stats: { topSpeed: 94.5, boostAmount: 3, boostType: "Charge", boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 69,  name: "La Fasta",                                    category: "Balanced",      stats: { topSpeed: 94.5, boostAmount: 4, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 70,  name: "Spine Buster",                                category: "Balanced",      stats: { topSpeed: 94.5, boostAmount: 2, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 71,  name: "2018 Ford Mustang GT",                        category: "Drifter",       stats: { topSpeed: 94.4, boostAmount: 3, boostType: "Charge", boostPower: 68.0,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1530, weightModifier: "x0.9",  banned: false } },
    { id: 72,  name: "Bone Shaker Unleashed",                       category: "Drifter",       stats: { topSpeed: 94.4, boostAmount: 5, boostType: "Bar",    boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 73,  name: "Carbide",                                     category: "Rocket",        stats: { topSpeed: 94.4, boostAmount: 3, boostType: "Bar",    boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 74,  name: "Cyber Speeder",                               category: "Rocket",        stats: { topSpeed: 94.4, boostAmount: 3, boostType: "Bar",    boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 75,  name: "16 Angels",                                   category: "Balanced",      stats: { topSpeed: 94.4, boostAmount: 3, boostType: "Charge", boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 76,  name: "Battle Spec",                                 category: "Balanced",      stats: { topSpeed: 94.4, boostAmount: 3, boostType: "Charge", boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 77,  name: "Bully Goat",                                  category: "Balanced",      stats: { topSpeed: 94.4, boostAmount: 4, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 78,  name: "1995 Mitsubishi Eclipse (F&F)",               category: "Swift",         stats: { topSpeed: 94.4, boostAmount: 5, boostType: "Charge", boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: true  } },
    { id: 79,  name: "Time Attaxi",                                 category: "Swift",         stats: { topSpeed: 94.4, boostAmount: 3, boostType: "Bar",    boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: false } },
    { id: 80,  name: "Rip Rod",                                     category: "Drifter",       stats: { topSpeed: 94.3, boostAmount: 3, boostType: "Charge", boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 81,  name: "Mad Manga",                                   category: "Rocket",        stats: { topSpeed: 94.3, boostAmount: 2, boostType: "Bar",    boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 82,  name: "El Segundo Coupe",                            category: "Balanced",      stats: { topSpeed: 94.3, boostAmount: 4, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 83,  name: "Hot Seat",                                    category: "Balanced",      stats: { topSpeed: 94.3, boostAmount: 5, boostType: "Charge", boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 84,  name: "Power Pistons",                               category: "Balanced",      stats: { topSpeed: 94.3, boostAmount: 3, boostType: "Charge", boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 85,  name: "Night Shifter",                               category: "Swift",         stats: { topSpeed: 94.3, boostAmount: 3, boostType: "Charge", boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: false } },
    { id: 86,  name: "HW450F [Bike]",                               category: "Bike",          stats: { topSpeed: 94.2, boostAmount: 5, boostType: "Bar",    boostPower: 131.5, driftBoostGain: 0.42, passiveBoostGain: 0.07, baseWeight: 400,  weightModifier: null,    banned: true  } },
    { id: 87,  name: "Ford Hot Heap",                               category: "Rocket",        stats: { topSpeed: 94.2, boostAmount: 3, boostType: "Charge", boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 88,  name: "Jack Hammer",                                 category: "Rocket",        stats: { topSpeed: 94.2, boostAmount: 3, boostType: "Charge", boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 89,  name: "LB Super Silhouette Nissan Silvia S15",       category: "Rocket",        stats: { topSpeed: 94.2, boostAmount: 4, boostType: "Bar",    boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 90,  name: "Datsun 240Z Custom (F&F)",                    category: "Balanced",      stats: { topSpeed: 94.2, boostAmount: 4, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: true  } },
    { id: 91,  name: "Reverb (Vert's)",                             category: "Balanced",      stats: { topSpeed: 94.2, boostAmount: 4, boostType: "Charge", boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 92,  name: "1993 Mercedes-Benz E 36 AMG Estate Custom",   category: "Swift",         stats: { topSpeed: 94.2, boostAmount: 5, boostType: "Charge", boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: true  } },
    { id: 93,  name: "Volkswagen Golf GTI",                         category: "Swift",         stats: { topSpeed: 94.2, boostAmount: 3, boostType: "Charge", boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: false } },
    { id: 94,  name: "Dodge Deora",                                 category: "Heavy",         stats: { topSpeed: 94.2, boostAmount: 3, boostType: "Charge", boostPower: 49.8,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 2350, weightModifier: null,    banned: false } },
    { id: 95,  name: "RD-05",                                       category: "Off-Road",      stats: { topSpeed: 94.1, boostAmount: 3, boostType: "Bar",    boostPower: 61.0,  driftBoostGain: 0.58, passiveBoostGain: 0.15, baseWeight: 1900, weightModifier: null,    banned: false } },
    { id: 96,  name: "Swamp Buggy",                                 category: "Off-Road",      stats: { topSpeed: 94.1, boostAmount: 5, boostType: "Charge", boostPower: 61.0,  driftBoostGain: 0.58, passiveBoostGain: 0.15, baseWeight: 1900, weightModifier: null,    banned: false } },
    { id: 97,  name: "Oldsmobile 442",                              category: "Drifter",       stats: { topSpeed: 94.1, boostAmount: 3, boostType: "Charge", boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 98,  name: "Street Creeper",                              category: "Drifter",       stats: { topSpeed: 94.1, boostAmount: 3, boostType: "Charge", boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 99,  name: "Street Creeper STH",                          category: "Drifter",       stats: { topSpeed: 94.1, boostAmount: 3, boostType: "Charge", boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 100, name: "Audi R8 LMS",                                 category: "Rocket",        stats: { topSpeed: 94.1, boostAmount: 3, boostType: "Charge", boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 101, name: "BMW M3 GT2",                                  category: "Rocket",        stats: { topSpeed: 94.1, boostAmount: 3, boostType: "Charge", boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 102, name: "Prototype H-24",                              category: "Rocket",        stats: { topSpeed: 94.1, boostAmount: 2, boostType: "Charge", boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 103, name: "Electro Silhouette",                          category: "Balanced",      stats: { topSpeed: 94.1, boostAmount: 3, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 104, name: "Technetium",                                  category: "Balanced",      stats: { topSpeed: 94.1, boostAmount: 3, boostType: "Charge", boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 105, name: "W Motors Lykan HyperSport (F&F)",             category: "Balanced",      stats: { topSpeed: 94.1, boostAmount: 3, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: true  } },
    { id: 106, name: "Back to the Future Time Machine",             category: "Swift",         stats: { topSpeed: 94.1, boostAmount: 3, boostType: "Charge", boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: true  } },
    { id: 107, name: "Custom Volkswagen",                           category: "Swift",         stats: { topSpeed: 94.1, boostAmount: 3, boostType: "Bar",    boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: true  } },
    { id: 108, name: "Splittin' Image II",                          category: "Swift",         stats: { topSpeed: 94.1, boostAmount: 4, boostType: "Bar",    boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: true  } },
    { id: 109, name: "Volkswagen Drag Bus",                         category: "Swift",         stats: { topSpeed: 94.1, boostAmount: 3, boostType: "Bar",    boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: true  } },
    { id: 110, name: "Dodge Charger SRT Hellcat Widebody (F&F)",    category: "Drifter",       stats: { topSpeed: 94.0, boostAmount: 4, boostType: "Charge", boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: true  } },
    { id: 111, name: "K.I.T.T.",                                    category: "Drifter",       stats: { topSpeed: 94.0, boostAmount: 3, boostType: "Bar",    boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 112, name: "Mod Rod",                                     category: "Drifter",       stats: { topSpeed: 94.0, boostAmount: 4, boostType: "Bar",    boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 113, name: "Corvette C8.R",                               category: "Rocket",        stats: { topSpeed: 94.0, boostAmount: 4, boostType: "Charge", boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 114, name: "Tooligan",                                    category: "Balanced",      stats: { topSpeed: 94.0, boostAmount: 2, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 115, name: "Honda Super Cub [Bike]",                      category: "Bike",          stats: { topSpeed: 93.9, boostAmount: 4, boostType: "Charge", boostPower: 131.5, driftBoostGain: 0.42, passiveBoostGain: 0.07, baseWeight: 400,  weightModifier: null,    banned: true  } },
    { id: 116, name: "Sand Burner",                                 category: "Off-Road",      stats: { topSpeed: 93.9, boostAmount: 5, boostType: "Bar",    boostPower: 61.0,  driftBoostGain: 0.58, passiveBoostGain: 0.15, baseWeight: 1900, weightModifier: null,    banned: false } },
    { id: 117, name: "Speed Bump",                                  category: "Off-Road",      stats: { topSpeed: 93.9, boostAmount: 4, boostType: "Bar",    boostPower: 61.0,  driftBoostGain: 0.58, passiveBoostGain: 0.15, baseWeight: 1900, weightModifier: null,    banned: false } },
    { id: 118, name: "RocketFire",                                  category: "Drifter",       stats: { topSpeed: 93.9, boostAmount: 3, boostType: "Charge", boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 119, name: "Lancia Rally 037",                            category: "Rally",         stats: { topSpeed: 93.9, boostAmount: 4, boostType: "Charge", boostPower: 69.6,  driftBoostGain: 0.58, passiveBoostGain: 0.15, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 120, name: "Ballistik",                                   category: "Swift",         stats: { topSpeed: 93.9, boostAmount: 3, boostType: "Charge", boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: false } },
    { id: 121, name: "Sudden Stop",                                 category: "Off-Road",      stats: { topSpeed: 93.8, boostAmount: 5, boostType: "Charge", boostPower: 61.0,  driftBoostGain: 0.58, passiveBoostGain: 0.15, baseWeight: 1900, weightModifier: null,    banned: false } },
    { id: 122, name: "Bassline",                                    category: "Drifter",       stats: { topSpeed: 93.8, boostAmount: 3, boostType: "Bar",    boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 123, name: "Jet Threat 3.0",                              category: "Rocket",        stats: { topSpeed: 93.8, boostAmount: 3, boostType: "Charge", boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 124, name: "16 Angels STH",                               category: "Balanced",      stats: { topSpeed: 93.8, boostAmount: 3, boostType: "Charge", boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 125, name: "Mercedes-Benz 300 SL",                        category: "Balanced",      stats: { topSpeed: 93.8, boostAmount: 3, boostType: "Charge", boostPower: 72.8,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1402, weightModifier: "x0.85", banned: false } },
    { id: 126, name: "2023 Nissan Z",                               category: "Swift",         stats: { topSpeed: 93.8, boostAmount: 4, boostType: "Charge", boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: true  } },
    { id: 127, name: "Rhinomite [MT]",                              category: "Monster Truck", stats: { topSpeed: 93.7, boostAmount: 6, boostType: "Bar",    boostPower: 42.9,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 3000, weightModifier: null,    banned: false } },
    { id: 128, name: "1994 Bugatti EB110 SS",                       category: "Balanced",      stats: { topSpeed: 93.7, boostAmount: 3, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 129, name: "Volkswagen Beach Bomb",                       category: "Heavy",         stats: { topSpeed: 93.7, boostAmount: 5, boostType: "Charge", boostPower: 49.8,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 2350, weightModifier: null,    banned: false } },
    { id: 130, name: "Fiat 500D Modificado",                        category: "Balanced",      stats: { topSpeed: 93.6, boostAmount: 4, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 131, name: "2014 Corvette Stingray Convertible",          category: "Swift",         stats: { topSpeed: 93.6, boostAmount: 3, boostType: "Charge", boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: false } },
    { id: 132, name: "Classic Packard",                             category: "Swift",         stats: { topSpeed: 93.6, boostAmount: 4, boostType: "Charge", boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: true  } },
    { id: 133, name: "Deora II",                                    category: "Heavy",         stats: { topSpeed: 93.6, boostAmount: 4, boostType: "Charge", boostPower: 49.8,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 2350, weightModifier: null,    banned: false } },
    { id: 134, name: "Hiway Hauler 2",                              category: "Heavy",         stats: { topSpeed: 93.6, boostAmount: 5, boostType: "Charge", boostPower: 49.8,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 2350, weightModifier: null,    banned: false } },
    { id: 135, name: "Alfa Romeo Giulia Sprint GTA (F&F)",          category: "Swift",         stats: { topSpeed: 93.5, boostAmount: 4, boostType: "Charge", boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: true  } },
    { id: 136, name: "Gunkster [MT]",                               category: "Monster Truck", stats: { topSpeed: 93.4, boostAmount: 4, boostType: "Bar",    boostPower: 42.9,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 3000, weightModifier: null,    banned: false } },
    { id: 137, name: "Race Ace [MT]",                               category: "Monster Truck", stats: { topSpeed: 93.4, boostAmount: 5, boostType: "Bar",    boostPower: 42.9,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 3000, weightModifier: null,    banned: false } },
    { id: 138, name: "Surf 'N Turf",                                category: "Drifter",       stats: { topSpeed: 93.4, boostAmount: 3, boostType: "Charge", boostPower: 90.8,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1020, weightModifier: "x0.6",  banned: true  } },
    { id: 139, name: "2016 Ford GT Race",                           category: "Rocket",        stats: { topSpeed: 93.4, boostAmount: 5, boostType: "Charge", boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 140, name: "Fast Fish",                                   category: "Rocket",        stats: { topSpeed: 93.4, boostAmount: 4, boostType: "Bar",    boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: true  } },
    { id: 141, name: "Synkro",                                      category: "Swift",         stats: { topSpeed: 93.4, boostAmount: 3, boostType: "Charge", boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: false } },
    { id: 142, name: "Blast Lane TH",                               category: "Bike",          stats: { topSpeed: 93.3, boostAmount: 4, boostType: "Bar",    boostPower: 131.5, driftBoostGain: 0.42, passiveBoostGain: 0.07, baseWeight: 400,  weightModifier: null,    banned: true  } },
    { id: 143, name: "Hollowback",                                  category: "Drifter",       stats: { topSpeed: 93.3, boostAmount: 3, boostType: "Charge", boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 144, name: "Solid Muscle",                                category: "Drifter",       stats: { topSpeed: 93.3, boostAmount: 3, boostType: "Charge", boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 145, name: "ATV [ATV]",                                   category: "Quad",          stats: { topSpeed: 93.3, boostAmount: 5, boostType: "Charge", boostPower: 113.2, driftBoostGain: 0.58, passiveBoostGain: 0.15, baseWeight: 800,  weightModifier: null,    banned: true  } },
    { id: 146, name: "2019 Mercedes-Benz A-Class",                  category: "Swift",         stats: { topSpeed: 93.3, boostAmount: 4, boostType: "Charge", boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: true  } },
    { id: 147, name: "Aston Martin 1963 DB5",                       category: "Swift",         stats: { topSpeed: 93.3, boostAmount: 3, boostType: "Charge", boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: false } },
    { id: 148, name: "Cadillac Seville by Gucci",                   category: "Swift",         stats: { topSpeed: 93.3, boostAmount: 3, boostType: "Bar",    boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: true  } },
    { id: 149, name: "Fiat 500 STH",                                category: "Swift",         stats: { topSpeed: 93.3, boostAmount: 4, boostType: "Bar",    boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: true  } },
    { id: 150, name: "2018 COPO Camaro SS",                         category: "Drifter",       stats: { topSpeed: 93.2, boostAmount: 3, boostType: "Charge", boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 151, name: "Count Muscula",                               category: "Drifter",       stats: { topSpeed: 93.2, boostAmount: 3, boostType: "Bar",    boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 152, name: "Rivited",                                     category: "Drifter",       stats: { topSpeed: 93.2, boostAmount: 3, boostType: "Bar",    boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 153, name: "Rodger Dodger STH",                           category: "Drifter",       stats: { topSpeed: 93.2, boostAmount: 3, boostType: "Charge", boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 154, name: "Impavido 1",                                  category: "Rocket",        stats: { topSpeed: 93.2, boostAmount: 4, boostType: "Bar",    boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 155, name: "Super Blitzen",                               category: "Rocket",        stats: { topSpeed: 93.2, boostAmount: 5, boostType: "Charge", boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: true  } },
    { id: 156, name: "Vulture",                                     category: "Rocket",        stats: { topSpeed: 93.2, boostAmount: 3, boostType: "Bar",    boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 157, name: "Audi Sport Quattro",                          category: "Rally",         stats: { topSpeed: 93.2, boostAmount: 5, boostType: "Charge", boostPower: 69.6,  driftBoostGain: 0.58, passiveBoostGain: 0.15, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 158, name: "Sharkruiser",                                 category: "Balanced",      stats: { topSpeed: 93.2, boostAmount: 3, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 159, name: "1985 Honda City Turbo II",                    category: "Swift",         stats: { topSpeed: 93.2, boostAmount: 5, boostType: "Charge", boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: true  } },
    { id: 160, name: "1955 Chevy",                                  category: "Drifter",       stats: { topSpeed: 93.1, boostAmount: 3, boostType: "Charge", boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 161, name: "Rodger Dodger",                               category: "Drifter",       stats: { topSpeed: 93.1, boostAmount: 3, boostType: "Charge", boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 162, name: "Cyber Speeder TH",                            category: "Rocket",        stats: { topSpeed: 93.1, boostAmount: 3, boostType: "Bar",    boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 163, name: "Power Rocket",                                category: "Balanced",      stats: { topSpeed: 93.1, boostAmount: 5, boostType: "Charge", boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 164, name: "Mattel Dream Mobile",                         category: "Swift",         stats: { topSpeed: 93.1, boostAmount: 5, boostType: "Charge", boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: true  } },
    { id: 165, name: "Mini Cooper S Challenge",                     category: "Swift",         stats: { topSpeed: 93.1, boostAmount: 6, boostType: "Bar",    boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: true  } },
    { id: 166, name: "Custom 1956 Ford Truck",                      category: "Heavy",         stats: { topSpeed: 93.1, boostAmount: 3, boostType: "Charge", boostPower: 49.8,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 2350, weightModifier: null,    banned: false } },
    { id: 167, name: "Sandivore",                                   category: "Off-Road",      stats: { topSpeed: 93.0, boostAmount: 4, boostType: "Charge", boostPower: 82.0,  driftBoostGain: 0.58, passiveBoostGain: 0.15, baseWeight: 1330, weightModifier: "x0.7",  banned: false } },
    { id: 168, name: "Quad Rod [ATV]",                              category: "Quad",          stats: { topSpeed: 93.0, boostAmount: 5, boostType: "Bar",    boostPower: 113.2, driftBoostGain: 0.58, passiveBoostGain: 0.15, baseWeight: 800,  weightModifier: null,    banned: true  } },
    { id: 169, name: "BMW 3.0 CSL Race Car",                        category: "Rocket",        stats: { topSpeed: 93.0, boostAmount: 4, boostType: "Bar",    boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 170, name: "Fiat 500",                                    category: "Swift",         stats: { topSpeed: 93.0, boostAmount: 4, boostType: "Bar",    boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: true  } },
    { id: 171, name: "Street Noz [Bike]",                           category: "Bike",          stats: { topSpeed: 92.9, boostAmount: 4, boostType: "Charge", boostPower: 131.5, driftBoostGain: 0.42, passiveBoostGain: 0.07, baseWeight: 400,  weightModifier: null,    banned: true  } },
    { id: 172, name: "FusionBusta",                                 category: "Drifter",       stats: { topSpeed: 92.9, boostAmount: 4, boostType: "Bar",    boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 173, name: "Sand Stinger [ATV]",                          category: "Quad",          stats: { topSpeed: 92.9, boostAmount: 4, boostType: "Bar",    boostPower: 113.2, driftBoostGain: 0.58, passiveBoostGain: 0.15, baseWeight: 800,  weightModifier: null,    banned: true  } },
    { id: 174, name: "24/Seven",                                    category: "Balanced",      stats: { topSpeed: 92.9, boostAmount: 3, boostType: "Charge", boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 175, name: "Hotweiler",                                   category: "Off-Road",      stats: { topSpeed: 92.8, boostAmount: 4, boostType: "Charge", boostPower: 61.0,  driftBoostGain: 0.58, passiveBoostGain: 0.15, baseWeight: 1900, weightModifier: null,    banned: false } },
    { id: 176, name: "Bone Shaker [MT]",                            category: "Monster Truck", stats: { topSpeed: 92.7, boostAmount: 5, boostType: "Bar",    boostPower: 42.9,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 3000, weightModifier: null,    banned: false } },
    { id: 177, name: "Custom Volkswagen Beetle",                    category: "Drifter",       stats: { topSpeed: 92.7, boostAmount: 4, boostType: "Bar",    boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 178, name: "HW Demo Derby [MT]",                          category: "Monster Truck", stats: { topSpeed: 92.6, boostAmount: 4, boostType: "Bar",    boostPower: 42.9,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 3000, weightModifier: null,    banned: false } },
    { id: 179, name: "Mega-Wrex [MT]",                              category: "Monster Truck", stats: { topSpeed: 92.6, boostAmount: 5, boostType: "Bar",    boostPower: 42.9,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 3000, weightModifier: null,    banned: false } },
    { id: 180, name: "Aristo Rat",                                  category: "Rocket",        stats: { topSpeed: 92.6, boostAmount: 3, boostType: "Bar",    boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 181, name: "Seared Tuner",                                category: "Balanced",      stats: { topSpeed: 92.6, boostAmount: 5, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 182, name: "Tiger Shark [MT]",                            category: "Monster Truck", stats: { topSpeed: 92.5, boostAmount: 4, boostType: "Bar",    boostPower: 42.9,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 3000, weightModifier: null,    banned: false } },
    { id: 183, name: "1932 Ford",                                   category: "Drifter",       stats: { topSpeed: 92.5, boostAmount: 5, boostType: "Bar",    boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 184, name: "1967 El Camino (F&F)",                        category: "Drifter",       stats: { topSpeed: 92.5, boostAmount: 4, boostType: "Bar",    boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: true  } },
    { id: 185, name: "Maelstrom",                                   category: "Drifter",       stats: { topSpeed: 92.5, boostAmount: 4, boostType: "Charge", boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 186, name: "Muscle Tone",                                 category: "Drifter",       stats: { topSpeed: 92.5, boostAmount: 5, boostType: "Bar",    boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 187, name: "HW Prototype 12",                             category: "Rocket",        stats: { topSpeed: 92.5, boostAmount: 4, boostType: "Charge", boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 188, name: "5 Alarm [MT]",                                category: "Monster Truck", stats: { topSpeed: 92.4, boostAmount: 4, boostType: "Bar",    boostPower: 42.9,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 3000, weightModifier: null,    banned: false } },
    { id: 189, name: "Rat-ified",                                   category: "Drifter",       stats: { topSpeed: 92.4, boostAmount: 3, boostType: "Charge", boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 190, name: "Twin Mill III",                               category: "Balanced",      stats: { topSpeed: 92.4, boostAmount: 4, boostType: "Bar",    boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 191, name: "Tricera-Truck",                               category: "Heavy",         stats: { topSpeed: 92.4, boostAmount: 5, boostType: "Bar",    boostPower: 49.8,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 2350, weightModifier: null,    banned: false } },
    { id: 192, name: "Vespa 90 SS Super Sprint [Bike]",             category: "Bike",          stats: { topSpeed: 92.3, boostAmount: 4, boostType: "Charge", boostPower: 131.5, driftBoostGain: 0.41, passiveBoostGain: 0.07, baseWeight: 400,  weightModifier: null,    banned: true  } },
    { id: 193, name: "Mountain Mauler",                             category: "Off-Road",      stats: { topSpeed: 92.3, boostAmount: 3, boostType: "Bar",    boostPower: 72.8,  driftBoostGain: 0.58, passiveBoostGain: 0.15, baseWeight: 1520, weightModifier: "x0.8",  banned: false } },
    { id: 194, name: "1990 Honda Civic EF",                         category: "Swift",         stats: { topSpeed: 92.3, boostAmount: 4, boostType: "Charge", boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: false } },
    { id: 195, name: "Tanknator",                                   category: "Heavy",         stats: { topSpeed: 92.3, boostAmount: 5, boostType: "Bar",    boostPower: 49.8,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 2350, weightModifier: null,    banned: false } },
    { id: 196, name: "1971 El Camino",                              category: "Drifter",       stats: { topSpeed: 92.2, boostAmount: 3, boostType: "Bar",    boostPower: 62.2,  driftBoostGain: 0.4,  passiveBoostGain: 0.06, baseWeight: 1700, weightModifier: null,    banned: false } },
    { id: 197, name: "Bigfoot [MT]",                                category: "Monster Truck", stats: { topSpeed: 92.1, boostAmount: 5, boostType: "Bar",    boostPower: 42.9,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 3000, weightModifier: null,    banned: false } },
    { id: 198, name: "Shark Bite",                                  category: "Balanced",      stats: { topSpeed: 92.1, boostAmount: 2, boostType: "Charge", boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 199, name: "Chicane",                                     category: "Balanced",      stats: { topSpeed: 91.9, boostAmount: 4, boostType: "Charge", boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 200, name: "Bye Focal II",                                category: "Swift",         stats: { topSpeed: 91.7, boostAmount: 3, boostType: "Bar",    boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: null,    banned: false } },
    { id: 201, name: "Bump Around TH",                              category: "Swift",         stats: { topSpeed: 91.6, boostAmount: 4, boostType: "Bar",    boostPower: 72.8,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1350, weightModifier: "x1",    banned: true  } },
    { id: 202, name: "Hot Wheels High",                             category: "Heavy",         stats: { topSpeed: 91.6, boostAmount: 6, boostType: "Bar",    boostPower: 49.8,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 2350, weightModifier: null,    banned: false } },
    { id: 203, name: "Invader",                                     category: "Heavy",         stats: { topSpeed: 91.6, boostAmount: 4, boostType: "Bar",    boostPower: 49.8,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 2350, weightModifier: null,    banned: false } },
    { id: 204, name: "Tanknator TH",                                category: "Heavy",         stats: { topSpeed: 91.5, boostAmount: 5, boostType: "Bar",    boostPower: 49.8,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 2350, weightModifier: null,    banned: false } },
    { id: 205, name: "Baja Bone Shaker",                            category: "Off-Road",      stats: { topSpeed: 91.0, boostAmount: 6, boostType: "Bar",    boostPower: 61.0,  driftBoostGain: 0.58, passiveBoostGain: 0.15, baseWeight: 1900, weightModifier: null,    banned: false } },
    { id: 206, name: "Bump Around",                                 category: "Swift",         stats: { topSpeed: 90.9, boostAmount: 5, boostType: "Bar",    boostPower: 78.2,  driftBoostGain: 0.51, passiveBoostGain: 0.11, baseWeight: 1215, weightModifier: "x0.9",  banned: true  } },
    { id: 207, name: "Bad to the Blade",                            category: "Rocket",        stats: { topSpeed: 90.2, boostAmount: 2, boostType: "Charge", boostPower: 78.2,  driftBoostGain: 0.41, passiveBoostGain: 0.06, baseWeight: 1250, weightModifier: null,    banned: false } },
    { id: 208, name: "Roller Toaster",                              category: "Heavy",         stats: { topSpeed: 90.1, boostAmount: 5, boostType: "Bar",    boostPower: 59.7,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 1880, weightModifier: "x0.8",  banned: false } },
    { id: 209, name: "Dragon Blaster",                              category: "Balanced",      stats: { topSpeed: 89.8, boostAmount: 3, boostType: "Charge", boostPower: 65.1,  driftBoostGain: 0.43, passiveBoostGain: 0.06, baseWeight: 1650, weightModifier: null,    banned: false } },
    { id: 210, name: "Night Burner",                                category: "Heavy",         stats: { topSpeed: 88.3, boostAmount: 5, boostType: "Bar",    boostPower: 49.8,  driftBoostGain: 0.9,  passiveBoostGain: 0.25, baseWeight: 2350, weightModifier: null,    banned: false } },
  ];


  // ---------- Tracks, grouped by creator ----------
  // Each creator is its own small object: { localId: "Track Name" }.
  // To add/remove a track, just add/remove a line here -- no need to
  // renumber anything else.

  const acceler = {
    1: "High Contrast",
    2: "50ShadesOfSpeed",
    3: "Shade of Speed",
    4: "Highway35 Leg 2",
    5: "Being Paid",
    6: "Highway35 Leg 4",
    7: "Highway35 Leg 3",
    8: "Highway35 Leg 1",
    9: "The Acceledrome",
    10: "Storm Realm",
    11: "Water Realm",
    12: "Fog Realm 1.0",
    13: "Cliffside Realm",
    14: "Clound 9",
    15: "Canyon Realm",
    16: "Desert Realm",
    17: "Some Candy?",
    18: "Dino Rampage",
    19: "Metro Realm 1.0",
  };

  const animax = {
    1: "Lost Media",
    2: "Tape: Ex_30E91",
    3: "Tainted Memory",
    4: "Tony's",
    5: "Beta Junk",
    6: "Paradon Prix",
    7: "Sigma Palace",
    8: "Neo Arcadia",
    9: "CosmicTyphoon F",
    10: "Mega City",
    11: "Astral Ascent",
    12: "Ooga Booga Slam",
    13: "Monolith MTRway",
    14: "Baja Betrayal",
    15: "Quantum Quasar",
    16: "Rally Alley",
    17: "Lab Sector",
    18: "Animax's Yard",
    19: "Shuttle Blast",
  };

  const beck = {
    1: "Home Turf",
    2: "Speed Green",
    3: "Speed Plaza",
    4: "Speed 268",
    5: "Beck's Coaster",
    6: "Pizza Park",
    7: "See You Again",
    8: "Around The Pole",
    9: "Overdrive Tempo",
    10: "Wild Wild Wild",
    11: "Memorize Me",
    12: "Rise Up WRU",
    13: "Lemon Flash",
    14: "Banana Stadium",
    15: "Amalfi Speedway",
    16: "Solar Speedway",
    17: "Banana Speedway",
    18: "Fossilology",
    19: "Jelly Jam",
    20: "Dine & Dash",
    21: "Patio Prowl",
    22: "Watch Your Head",
    23: "Call Your Dr.",
    24: "Rough & Tumble",
    25: "Alloy Arena",
    26: "Cave Explorer",
    27: "Homemade Drifts",
    28: "Rollin Timbers",
    29: "Rooftop Royal",
    30: "High Tide",
    31: "Orbital Descent",
    32: "Void Escape",
    33: "Putt Putt Rush",
    34: "Berry Loop",
    35: "Neon Avalanche",
    36: "Pachy Park",
    37: "Speed Order",
    38: "Speed Garden",
    39: "The Wagon Cup",
    40: "Speed 101",
  };

  const biyzor = {
    1: "Powerbank",
    2: "BakerVerse",
    3: "Hq for 30",
    4: "Jedi Temple",
    5: "Cairn Toul",
    6: "Chicken Coop",
    7: "HQ430",
    8: "Death Star",
    9: "Mr Meatball",
    10: "Falls of Biyz",
    11: "Loft Conversion",
    12: "R2-Detour",
    13: "Boonta Eve",
    14: "Citadel Tower",
    15: "Star Wars",
    16: "Neon Tokyo",
    17: "Gates Of Hell",
    18: "Terminal V WRU",
    19: "Fushia City",
    20: "Cerulean City",
    21: "HauntdWasteland",
    22: "New World",
    23: "Pillar Patio",
    24: "Discoland",
    25: "Pewter City",
    26: "Indigo Plateau",
    27: "Saffron City",
    28: "The Bowlarama",
    29: "Moment Of Truth",
    30: "Grand National",
    31: "Viridian City",
    32: "Cinnabar Island",
    33: "Celadon City",
    34: "Vermillion City",
    35: "Space Lab",
    36: "Kewx",
    37: "4. Ride BGP",
    38: "Gerudo Valley",
    39: "Lantern Run",
    40: "Zonia Speedway",
    41: "Snappy Pasta C",
    42: "Frost Biyt B",
    43: "Street Fiyter A",
    44: "2. Home BGP",
    45: "1. Gas BGP",
    46: "3. Launch BGP",
    47: "Rocky Road",
    48: "Particle Blast",
    49: "Tuna, no crust",
    50: "Station Sunset",
    51: "Bum Chin Billy",
    52: "Dragon's Den",
    53: "City Of Wind",
    54: "Biyz Shootout",
    55: "Kuro Isles",
    56: "Into The Vortex",
    57: "Thats My Garden",
    58: "Thats My Pizza!",
    59: "Speed Wall 2",
    60: "Dealer Bust",
    61: "Take Me Away",
    62: "Only Up",
    63: "Sun Catcher",
    64: "Kuro Hideout",
    65: "Mantine Circuit",
    66: "Wildlife Tour",
    67: "Dino Void",
    68: "Hangar Z",
    69: "Black Hole Race",
    70: "Cheeky Cheddar",
    71: "Galactic Gallop",
    72: "Offroad Pizza",
    73: "Sheikah Clash",
    74: "Clear The Desk",
    75: "Send It?",
    76: "Big Rig Blast",
    77: "Wave Riders",
    78: "Dream Eater",
    79: "Flight Academy",
    80: "Flight School",
    81: "Bike Park",
    82: "Ice Cream Rush",
    83: "Biyz Paradise!",
    84: "Lantern Race",
    85: "Bready2Crumble?",
    86: "Dino Biyz",
    87: "Biyz Fun House",
    88: "Holly's Track",
    89: "Rainbow Biyz",
    90: "Skyloft",
    91: "The Lost Woods",
    92: "Arbiters Ground",
    93: "Skin Tight 2",
    94: "Speed Corp",
    95: "Armogohma",
    96: "Terminal V",
    97: "Biyz Backyard",
    98: "Tricky Delivery",
    99: "SuperDrifter2",
    100: "Biyz Hq",
    101: "Gold Miyn",
    102: "Diner Trouble",
    103: "The Bramble",
    104: "TastyGoodness",
  };

  const bread = {
    1: "B-Day Cake Bash",
    2: "The Grain Prix",
    3: "Cake Perfected",
    4: "Pumpkin Party",
    5: "Danger Zone",
    6: "Candy BAR Twist",
    7: "Hocking Heights",
    8: "Ridgeline Rush",
    9: "Watkins Glen",
    10: "MartinsvilleNAS",
    11: "Le Mans 24 Hours",
    12: "Aces High",
    13: "Let's Cook!",
    14: "Heisenburger",
    15: "Le Mans 24 Hour",
    16: "Blue Razz PT EX",
    17: "Cherry PT",
    18: "Brown Sugar PT",
    19: "Unfrosted PT",
    20: "Bread Blinders",
    21: "The Cal-Zone",
    22: "Crepe Colosseum",
    23: "The Exhaust Fan",
    24: "Rye Rally",
    25: "WhereEaglesDare",
    26: "ExtraCrustrial",
    27: "Jelly Jam",
    28: "Ribcage Rush",
    29: "Banana Bonanza",
    30: "Rocky Road",
    31: "Bonbon Blitz",
    32: "Jellybean Jumps",
    33: "Pizza Plaza",
    34: "Crouton Cliffs",
    35: "Pita Palace",
    36: "Bread's Bakery",
    37: "ThreeLayer Cake",
  };

  const copper = {
    1: "Rule Breaker",
    2: "Snake!!!!!!!!!!",
    3: "Sea Krait",
    4: "Garden snake",
    5: "Renegade Voyage",
    6: "Rat Snake",
    7: "The Buzzard",
    8: "ms Earth wip",
    9: "Zion Rally",
    10: "Claustrophobia",
    11: "Diamondback WRU",
    12: "Donkey Kong ?",
    13: "Copperhead 2h",
    14: "Copperhead HSR",
    15: "shamalamamoomoo",
    16: "The Diamondback",
    17: "Shablamo!",
    18: "Martian Ruckus",
    19: "Aussie Tour",
    20: "SalamiSlalom Cu",
    21: "Ice Ice Baby",
    22: "Parkour civil",
    23: "The Circus act",
    24: "house o horror",
    25: "The Invaders!",
    26: "jungle gym",
    27: "hsr wip 3",
    28: "4/11 crawlspace",
    29: "hsr can3 wip v2",
    30: "a stupid track",
    31: "time crunch",
    32: "Order up!",
    33: "fossil assembly",
    34: "Floral fury",
    35: "Sussy Circuit",
    36: "ms relapse",
    37: "Wind Breaker",
    38: "Jurassic Rally",
    39: "Down to Earth",
    40: "rally family",
    41: "neon shuffle",
    42: "diesel vertigo",
    43: "FlashFlood",
    44: "Grass Attack",
    45: "comet remanent",
    46: "i scream",
    47: "POWAH ! Stadium",
    48: "180s R Us !",
    49: "need gas ?",
    50: "meteor shower",
    51: "cupro-mania v2",
    52: "ms desending",
    53: "ms molten steel",
    54: "ms  cyclone",
    55: "village maniacs",
    56: "ms gold sprint",
    57: "ms coldsnap",
    58: "ms hell's wrath",
    59: "ms route 29",
    60: "ms plantation",
    61: "ms obilisk",
    62: "ms raibow falls",
    63: "ms quicksand",
    64: "ms serpant bog",
    65: "ms trainwreck",
    66: "ms sewer rats",
    67: "ms wood chipper",
    68: "ms death valley",
    69: "summer vertigo",
    70: "Snakeoil rapids",
    71: "escalator bash",
    72: "ready2order?",
    73: "couch crash 2",
    74: "shelf top air",
    75: "couch crash",
    76: "fossil study",
    77: "check in derby",
    78: "highway to hell",
    79: "indoor banks",
    80: "dine and dash",
    81: "windy jungle",
    82: "burning bridge",
  };

  const crux = {
    1: "Fighter Ace CX",
    2: "Get Started CX",
    3: "Going Wide CX",
    4: "Guttersnipe CX",
    5: "Hole 2 Rally CX",
    6: "Out Run CX",
    7: "Tree Tech CX",
  };

  const dandube = {
    1: "Bumble Rumble",
    2: "T-rexus-nexus",
    3: "Van-tastic",
    4: "Bubba Yugga",
    5: "Tim Turn Table",
    6: "Bash-enheimer",
    7: "PikesArePeakin",
    8: "Speed of Saturn",
  };

  const dish = {
    1: "Putt Putt",
    2: "Neo Crossroads",
    3: "Timmy's Tires",
    4: "Speed Box",
    5: "Water Bomb",
    6: "Flash Flood",
    7: "Downhill Detour",
    8: "Trick City",
  };

  const drcr = {
    1: "Bricked Up",
    2: "Dance Floor Dash",
    3: "Dr's Challenge",
    4: "Home Invasion",
    5: "Long Way ‘Round",
    6: "Passing Wind",
    7: "Pushback",
    8: "Quick & Dirty",
    9: "Racer's Run",
    10: "Rekt'em Rally",
    11: "Rooftop Rally",
    12: "Skyhigh Drifts",
    13: "Smasher Pass",
    14: "The Back Nine",
    15: "Trick or Treat",
    16: "Tyrant King",
    17: "Wood Rider",
  };

  const elias = {
    1: "Reactor Factor",
    2: "Circuit Breaker",
  };

  const emily = {
    1: "Ice V",
    2: "3rd Interval",
    3: "Balancing Act 2",
    4: "Cold Reactor",
    5: "DesyncChallenge",
    6: "Engulfed Castle",
    7: "Ice V",
    8: "Jumpstart",
    9: "Kiemurteleva",
    10: "Portaikko",
    11: "Power Steer",
    12: "Serial Thrilla",
    13: "Steelhead",
    14: "Sun Princess",
    15: "Void Seekers",
    16: "Whats Her Name?",
    17: "Windy Landscape",
    18: "Your Majesty",
  };

  const f1wolf = {
    1: "Advance.DSlayer",
    2: "Baconator &Soda",
    3: "Wolf Pack",
    4: "Ready...GO!!",
    5: "ShapeThe Future",
    6: "Hangout Spot 2",
    7: "Advance.DSlayer",
    8: "Hangout Spot",
    9: "Crazy Call 1!!!",
    10: "T-Rex LockDown!",
    11: "SuperCharged!",
    12: "Da People",
    13: "LGL 5V2",
    14: "The Dust Land",
    15: "LGL 2 R,Part2",
    16: "Sweft'sShowdown",
    17: "Go Wild 2 !",
    18: "Let's Get Lit 4",
    19: "HeavyDuty Style",
    20: "Let's Get Lit 5",
    21: "LGL 2 Remake",
    22: "Dream Chaser",
    23: "HandlingPhsics1",
    24: "Don't Stop T DJ",
    25: "Let's Get Lit3!",
    26: "Edge Of T Earth",
    27: "Road Work",
    28: "Rock SomeMetal!",
    29: "Driving THR!GP4",
    30: "Tire Smoke GP11",
    31: "Turbo Lover.GP3",
    32: "R2.Break Them",
    33: "Round2.InsaneGP",
    34: "Dirt Rally.RGP7",
    35: "Paradise.RGP8",
    36: "No Limit's.RGP5",
    37: "ROUND1.The Flow",
    38: "THE GRID.RGP2",
    39: "New Comers.RGP1",
    40: "Gaming Club.GP1",
    41: "Acid Trap,R1",
    42: "Alert.CODE RED!",
    43: "RIVALS",
    44: "The Underground",
    45: "Poison Lab",
    46: "LET'S Get Hype!",
    47: "The Hunter.GP4",
    48: "CrazyCall SGP13",
    49: "Extreame S.GP2",
    50: "DriveClub S.GP5",
    51: "Let's Hunt .GP3",
    52: "HWDiner SP.GP7",
    53: "HW Pit Stop GP8",
    54: "Speedstir GP10",
    55: "Draw!SP.GP9",
    56: "The Rush!SP.GP6",
    57: "LET'S GO!.RGP8",
    58: "Nice View.RGP6",
    59: "FIRE UP!.RGP10",
    60: "High end.R GP9",
    61: "LET'S Get Lit 2",
    62: "D.THE SLAYER!!!",
    63: "Practice Mode 1",
    64: "DRIFT BABY YA!",
    65: "Gold Mine",
    66: "Let's Get Lit!",
    67: "WolfVengence",
    68: "Go Wild! GP12",
    69: "Ch3.Remastered",
    70: "Tires burn GP11",
    71: "Round1.R.GP11",
    72: "TR.GR.Chamber 2",
    73: "Special event 2",
    74: "Special event 1",
    75: "RGP12.Round2 E",
    76: "TR.GR. chamber",
  };

  const fidestic = {
    1: "HW Enduro",
    2: "Small Treatz",
    3: "Dawn Well",
    4: "Orthodox I",
    5: "Widow Maker",
    6: "Speed Stalker",
    7: "Small Treat",
    8: "Orthodox Alpha",
    9: "Woven Valley",
    10: "Orthodox Delta",
    11: "Mach X-tinction",
    12: "Mud Bowl",
    13: "TERRANOVA GP",
    14: "The Chasm",
    15: "Vertigo Ring",
    16: "Split The Atom",
    17: "Timewarp Enduro",
    18: "Speed Stalker",
  };

  const frost = {
    1: "Mt. Basher",
    2: "Vent Rally",
    3: "Power Slider",
    4: "Jump Jets",
    5: "Pizza Rolls",
    6: "KikoDayo",
    7: "Lilium",
  };

  const garnarbles = {
    1: "Turn Up",
    2: "Cooling Station",
    3: "Slow Down fr",
    4: "Speed Winder",
    5: "GRN Brake Early",
  };

  const gore = {
    1: "Taco Bell :3",
    2: "Prologue",
    3: "Midnight Stroll",
    4: "Dust Bowl",
    5: "The Wall",
    6: "Kuro-Khana",
    7: "Sunset Drive",
    8: "Lumberjack Trail",
    9: "Snake's Nest",
    10: "DeadfallJnction",
    11: "Jurassic Jam",
    12: "The Pretender 2",
    13: "Industrial Riot",
    14: "Rally RoadRage!",
    15: "Start The Fire",
  };

  const gunner = {
    1: "It's Payday!",
    2: "On The Railroad",
    3: "Skål",
    4: "Biskotso",
    5: "Voidwalker",
    6: "In Overdrive",
    7: "8BitsAreScary!",
    8: "Once a Heister",
    9: "Phenomenon",
    10: "GET ENUF",
    11: "Arcade Crusade",
    12: "Mini Drift",
    13: "Backyard Dreams",
    14: "Taken Seats",
    15: "Showrunner",
    16: "The Red Line",
    17: "Spectrum Rush",
    18: "Cosmic Drift",
    19: "Motor City",
    20: "Ancient Assault",
    21: "Platinum",
    22: "Balcony Burners",
    23: "Unleashed Prix",
    24: "Autumn Ride",
    25: "Tower Rally",
    26: "Outer Banked",
    27: "History Runner",
    28: "The Heirloom",
    29: "Med Bay Run",
    30: "Column of Power",
    31: "Scores of Power",
    32: "Timber of Power",
    33: "History Haulers",
    34: "Bound Exertion",
    35: "Ineffable Bend",
    36: "Backyard Bash",
    37: "Adagio Loop",
    38: "High Alert",
    39: "Swerve Station",
    40: "Fast & Strange",
    41: "Woodwork Avenue",
    42: "The Vaporbeat",
    43: "Petrol Passion",
    44: "The Blind Drive",
    45: "Street Surge",
    46: "Home Wreckers",
    47: "Evening Tour",
    48: "Pinewood Heat",
    49: "Hangar Showdown",
    50: "Bygone Drifts",
    51: "Final Toll",
    52: "Hometown Rally",
    53: "Vent-Way Aces",
    54: "Rushing Gambit",
    55: "Cylinder Shift",
    56: "Nowhere Fast",
    57: "Compact Vector",
    58: "Day Burner",
    59: "Mineshaft Rush",
    60: "Dust Bowl Riot",
    61: "Minimum Pay Way",
    62: "Shelved Speed",
    63: "RetroRevolution",
    64: "Dirty Disasters",
    65: "Living Byway",
    66: "Prime Direction",
    67: "Neptunian Rave",
    68: "Cityside Dash",
    69: "Dining Dashers",
    70: "Nebulous Nets",
    71: "Blitz Skirmish",
    72: "Violet City",
    73: "Azalea Town",
    74: "Goldenrod City",
    75: "Ecruteak City",
    76: "Cianwood City",
    77: "Olivine City",
    78: "Mahogany Town",
    79: "Blackthorn City",
    80: "Indigo Plateau",
    81: "Hi-Score Frenzy",
    82: "Octane Heat",
    83: "River Raceway",
    84: "StationSpeedway",
    85: "COTA F1",
    86: "Rhythm Rush",
    87: "Velocity Cross",
    88: "Ultimate Scorch",
    89: "Fossils Reborn",
    90: "Familiar Nitro",
    91: "Just Numbers",
    92: "Go For Broke",
    93: "Trailer Trouble",
    94: "Mischief Mayhem",
    95: "Sunlit Crest",
    96: "Pasta Fall",
    97: "Refueled Drive",
    98: "Bygone Wisdom",
    99: "Game Night",
    100: "Premium Grade",
    101: "Feral Freeway",
    102: "8-Bit Method",
    103: "Drift of Kin",
    104: "Green Scuffle",
    105: "Long Way Round",
    106: "Silver Way",
    107: "King’s Descent",
    108: "Buster Circuit",
    109: "SuperNoon Speed",
    110: "Tower of Heat",
  };

  const juampee = {
    1: "J- Hammerhead",
    2: "J- NoLeafClover",
    3: "HillClimbRacing",
    4: "J-Chopis Centis",
    5: "GO GO GO GO!",
    6: "J-Airplane Mode",
    7: "J-TheGuillotine",
    8: "J- Learn to Fly",
    9: "Gusty Ghouls KM",
    10: "J- The Defiant",
    11: "J- Betrayer",
    12: "J- In Waves RS",
    13: "J- Nostalgia 05",
    14: "J- Antimatter",
    15: "J- Nostalgia 04",
    16: "J- The Phalanx",
    17: "J-CountingWorms",
    18: "J- Jormungandr",
    19: "J- Dragula B",
    20: "J- WebsWeWeaveA",
    21: "J- Nostalgia 03",
    22: "J- Nostalgia 02",
    23: "J-CoachSurfing",
    24: "J- Nostalgia 01",
  };

  const judge = {
    1: "Cardamom Cruise",
    2: "Blind Rage",
    3: "Galvanizer",
    4: "WRU Tornado Tim",
    5: "Mag-nanimous",
    6: "Siren Charms",
    7: "Galvinizer",
    8: "Horizon's Edge",
    9: "Meet 'n Greet",
    10: "WRU Tornado Tim",
    11: "Aggressiondrome",
    12: "Mag-nanimous",
    13: "Charged Curves",
    14: "Dragon's Drive",
    15: "Field Research",
  };

  const kami = {
    1: "Shipwrecked",
    2: "Nightmarathon",
    3: "Orochi Road",
    4: "The End is Nigh",
    5: "HighNoon HiJinx",
    6: "Off The Trail",
    7: "Propane Peril",
    8: "Fear Factory TR",
    9: "Crimson Cube",
    10: "Cosmic Cruise",
    11: "Night of Fright",
    12: "Ion Impulse",
    13: "Hyper Haulers",
    14: "Ghost Riders",
    15: "UFOs & Big Rigs",
    16: "Loops of Uranus",
    17: "Wily Fortress",
    18: "Carpet Creepers",
    19: "Goo Lagoon C",
    20: "The Ramshackle",
    21: "Celestial Blitz",
    22: "Burnin' Rubber",
    23: "Gas Guzzler",
    24: "Hectic Horizons",
    25: "Dusty Descent",
    26: "AkinaTouge Pure",
    27: "Akina Touge",
    28: "Speedy Slalom",
    29: "Tread Ripper",
    30: "Off'n On",
  };

  const kiko = {
    1: "Redlight Ave",
    2: "Feet the Beast",
    3: "Speed Addiction",
    4: "Breaking Square",
    5: "Re-Hydrated",
    6: "643 Turkish",
    7: "Kill a Fraud",
    8: "Lord's Delight",
    9: "Shack Attack",
    10: "Birthday Run",
    11: "Organic Panic",
    12: "Super Saloon",
    13: "Laser Line",
    14: "Hell's Kitchen",
    15: "Club Bizarre",
    16: "Zeitgeist",
    17: "Force Skin",
    18: "X-mas Burnout",
    19: "Santa's Sled",
    20: "Christmas Land",
    21: "Secret Santa",
    22: "The Duelist",
    23: "Garden Double",
    24: "Stevenson Road",
    25: "Tower of Doom",
    26: "Cranium Cruise",
    27: "Drift Plaza",
    28: "Mars Hydro",
    29: "Botanic Panic",
    30: "Electric Ave",
    31: "Starlight Rush",
    32: "Blue Wave",
    33: "No Jokes",
    34: "Wild Hog",
    35: "Gasoline BBQ",
    36: "Space Force 68",
    37: "Speedy Gonzales",
    38: "Genesis Plus",
    39: "Cherry Pick",
    40: "Genesis",
    41: "Pistachio Ave",
    42: "Pizza Time!",
    43: "Arcade Rush",
    44: "Ratchet Rodeo",
    45: "Mainus on Fire",
    46: "Secret Track",
    47: "T-Rex Revenge",
    48: "Danger Diner X",
    49: "Breaking Point",
    50: "Blast it!",
    51: "Spacewing",
    52: "Roadworks",
    53: "Hybrid Theory",
    54: "Hyper Blur",
    55: "Mirror's Edge",
    56: "Asphalt Cowboy",
    57: "Thrillseeker",
    58: "Jurassic Falls",
    59: "Green Arrow",
    60: "Acceledrifters",
    61: "Stunt Town",
    62: "Hard Rock Cafe",
    63: "Stunt Trial",
    64: "Super Aarshnado",
    65: "Dino Twist",
    66: "Rock Roller",
    67: "Lightning Rush",
    68: "Prepare to die",
    69: "Scorpion Rally",
    70: "Cannonball",
    71: "Walligator",
    72: "Extinction",
    73: "Quantum Pursuit",
    74: "Gator Garden",
    75: "Duskfall Derby",
    76: "2 Line 2 Ride",
    77: "Velocicoaster",
    78: "Reptile Run",
    79: "Grashopper",
    80: "Gold Mine",
    81: "The Voyage",
    82: "Line Rider",
    83: "Arcade Action",
    84: "Blue Stars",
    85: "Highscore Rush",
    86: "T-Rex Rush",
    87: "Sunday Circus",
    88: "Free Candy",
    89: "Stargate",
    90: "Snake Eyes",
  };

  const mickey = {
    1: "Thrash-Inator",
    2: "Bashers Delight",
    3: "WRU Thunderdome",
    4: "Marina Madness",
    5: "Barracuda Hiway",
  };

  const mog = {
    1: "Moggoween 2023",
    2: "Mogroads",
    3: "Mog's Balcony",
    4: "Mog's Bones",
    5: "Mog's Bounce",
    6: "Mog's Boxes",
    7: "Mog's Break",
    8: "Mog's Breakfast",
    9: "Mog's Cash",
    10: "Mog's Check-In",
    11: "Mog's Clash",
    12: "Mog's Clean-Up",
    13: "Mog's Counter",
    14: "Mog's Dynamite",
    15: "Mog's Egg",
    16: "Mog's Escalator",
    17: "Mog's Exhibit",
    18: "Mog's Feet",
    19: "Mog's Fossil",
    20: "Mog's Gaming",
    21: "Mog's Golf Clap",
    22: "Mog's Grass",
    23: "Mog's Highscore",
    24: "Mog's Hoops",
    25: "Mog's Kitchen",
    26: "Mog's Ladder",
    27: "Mog's Mine",
    28: "Mog's Mouth",
    29: "Mog's Neon",
    30: "Mog's Overlook",
    31: "Mog's Par",
    32: "Mog's Petrolium",
    33: "Mog's Pinball",
    34: "Mog's Shelter",
    35: "Mog's Signs",
    36: "Mog's Slides",
    37: "Mog's Sofa",
    38: "Mog's Sphere",
    39: "Mog's Table",
    40: "Mog's Tickets",
    41: "Mog's Trash",
    42: "Mog's Treehouse",
    43: "Mog's Underdeck",
    44: "Mog's Van",
    45: "Mog's Wagon",
    46: "Mog's Waterway",
    47: "Mog's Windmill",
    48: "Mog's Windows",
  };

  const pato = {
    1: "F-Zero Big Blue",
    2: "Capricorn",
    3: "Maple Treeway",
    4: "Taurus",
    5: "Aries",
    6: "RedBull Soapbox",
    7: "Chelsea Dagger",
    8: "Pinecone",
    9: "Wonder of U",
    10: "Swordfish Mk2",
    11: "Cancer",
    12: "Virgo",
    13: "Sagittario",
    14: "Scorpio",
    15: "Libra",
    16: "Leo",
    17: "Crankshaft Bay",
    18: "Leviathan",
    19: "Flight School",
    20: "Riverside Rally",
    21: "Agni Kai",
    22: "Dude the 2st",
    23: "Dude Nitro",
    24: "Tech-Challenge",
    25: "Yggdrasil",
    26: "Waluigi Pinball",
    27: "Botanica C",
    28: "Dr. Light's Lab",
    29: "Criss Cross",
    30: "Atari GP",
    31: "Slip n' Slide",
    32: "Gator's Tribute",
    33: "The Arena",
    34: "Tomahawk",
    35: "Casa Cristo",
    36: "Arco di Firenze",
    37: "Fire Nation",
    38: "Central Highway",
    39: "Do a flip!",
    40: "Amelia's Sky",
    41: "Dino Drift",
    42: "X-Perimental",
    43: "Galaxy Pegasus",
    44: "HW Aquapark",
    45: "Winter Solstice",
    46: "8-Bit Powerline",
    47: "Leap Of Faith",
  };

  const q5rap = {
    1: "WILD WAY",
    2: "SMASHED APPLE",
    3: "THE LAST KISS",
    4: "CHRISTMAS NIGHT",
    5: "ALISS HEART",
    6: "THE BACKROOMS",
    7: "CRAZY CIRCUS",
    8: "FOUR DIMENSIONS",
    9: "AUTUMN DOORS",
    10: "THE HIGH RACE",
    11: "GOLD BOSS FIGHT",
    12: "WOLF BIRTHDAY",
    13: "HW LIGHT SHOW",
    14: "WONDERLAND",
    15: "HOW TO RACE !?",
    16: "THE HIGH ROOM",
    17: "FREE WAYS BOSS",
    18: "MOO BOSS FIGHT",
    19: "AT NIGHT",
    20: "THE COOL ROOMS",
    21: "SUNNY DAY 1960",
    22: "BEACH DAY",
    23: "DANGEROUS WAYS",
    24: "SNOWY NIGHT",
    25: "OLDTIMES",
    26: "FREE WAYS 1999",
    27: "RED AND BLUE",
    28: "BIGMOO",
    29: "SEWAGE PIPES",
    30: "HOTDAY",
    31: "1987",
    32: "RACE 2 U",
    33: "FREE WAYS 2077",
    34: "666",
    35: "SCP 999",
    36: "ice cream shop",
    37: "THE HIGH CITY",
    38: "SPACE STATION",
    39: "X5X",
    40: "GO TO THE LIGHT",
    41: "WIND ROOMS",
    42: "TOYS STORE",
    43: "THE BIG FACTORY",
    44: "GOLDS BOSS FIGHT",
    45: "UP&DOWN BOSS",
    46: "ICE CREAM SHOP",
    47: "HIGHWAY",
    48: "IT'S A COOL DAY",
    49: "LOOPS AND LOOPS",
    50: "SUNNY SKY",
    51: "RACE IN HEAVEN",
    52: "36 days",
    53: "THEONEANDONLY",
    54: "THE DOORS",
    55: "B HAPPY ^_^",
    56: "TREE DAY",
    57: "2 WAYS BOX",
    58: "ROOFS",
    59: "GAS OR NOT !",
    60: "FREE WAYS HW2",
    61: "Q BOSS FIGHT 8",
    62: "4 FUN !",
    63: "2050",
    64: "5!",
    65: "FAIRY TALE 3",
    66: "FAIRY TALE 2",
    67: "FAIRY TALE",
    68: "SKY RACE",
    69: "AFTER NIGHT",
    70: "SO ???",
    71: "TIME TO GO UP",
    72: "THE COOL ROOM",
    73: "Q BOSS FIGHT 4",
    74: "LETS GO OUT",
    75: "G LIGHT",
    76: "DEEP SLEEP",
    77: "THE GAS RACE",
    78: "AFTERNOON",
    79: "Q BOSS FIGHT II",
    80: "THE BAD DAY",
    81: "SALOON",
    82: "THE 4 WAYS",
    83: "11/11",
    84: "Q BOSS FIGHT 1",
    85: "AND WHAT?",
    86: "QBF 99",
    87: "THE D LOOP",
    88: "UP AND DOWN",
    89: "2 + 2",
    90: "ONE WAY DAY",
    91: "SUNNY DAY",
    92: "THE DEEP LIGHT",
    93: "GOLD DAY",
    94: "HWU DREAM",
    95: "TIMEROOM",
    96: "OUTSIDE",
    97: "CITY LIGHT",
    98: "the Q DAY",
  };

  const rj = {
    1: "Dark Matter Run",
    2: "Drawn Too Quick",
  };

  const shatter = {
    1: "Agnosia Engineβ",
    2: "Omechanica",
    3: "Love Triangle 2",
    4: "Autumn Wind",
    5: "B: Dataweave",
    6: "Cold Storage",
    7: "Era of Chroma",
    8: "Fracture",
    9: "Frostbite II",
    10: "Gene Splicers",
    11: "Heart Tremors B",
    12: "Hoedown Hijinx",
    13: "Magnomancy",
    14: "Mulch Maelstrom",
    15: "Patagium",
    16: "Pitstop",
    17: "Remington",
    18: "Table Scraps II",
    19: "The Gunslinger",
    20: "Vertebraceway",
  };

  const swole = {
    1: "Powdered Donut",
    2: "Victory Lap",
    3: "The Crossfire",
    4: "EMPTY DIARY",
    5: "LOCK IN",
    6: "MOBB1N' OUT",
    7: "HOLLOVV PO1NT5",
    8: "5H4DOVV T4LK",
    9: "R3D TH1RT33N",
    10: "B1T3 B4CK",
    11: "4RT1F1C14L",
    12: "D1V1S1ON4RY",
    13: "VV34PON1Z3D",
    14: "OBL1V1ONS'5 P34K",
    15: "OV3RK1LL",
    16: "Midinght Run",
    17: "George's Gorge",
    18: "Venomosity",
    19: "Signal Lost",
    20: "Rodeo Showdown",
    21: "Truck Trauma",
    22: "Central Core",
    23: "Seven Beers",
    24: "Black Banners",
    25: "Cannonball Run",
    26: "Venomosity",
    27: "Rodeo Showdown",
    28: "Signal Lost",
    29: "RDY4TAKEOFF",
    30: "Treasure Map",
    31: "Swole HQ",
    32: "Concrete Jungle",
    33: "Duct Derby",
    34: "Haunter",
    35: "Deathfire Grasp",
    36: "Fusions Reborn",
    37: "Jump Heaven",
    38: "RiptideWavepool",
    39: "Galleon's Grave",
    40: "Turbulent Skies",
    41: "Giggle",
    42: "DXM Foundr SG",
    43: "Mash Potato SG",
    44: "Watertower Wash",
    45: "Banana Loaf SG",
    46: "Toothless SG",
    47: "Hall of Fame",
    48: "Riptide Rush SG",
  };

  const trd = {
    1: "IWalkAheadOfYou",
    2: "BaguetteRevenge",
    3: "Boneyard Drifts",
    4: "BackyrdShowdown",
    5: "Around-A-House",
    6: "Bat Shot",
    7: "Whe3ñs Of NeOn",
    8: "Slots Racerz V2",
    9: "HeavenlyFreedom",
    10: "Wishing Well",
    11: "I... Am Steve!!",
    12: "Fire and Flames",
    13: "Launch Test",
    14: "Mailbu Pier",
    15: "IWalkAheadOfYou",
    16: "Level Up",
    17: "All I Do Is Win",
    18: "Goliath",
    19: "Eat Dirt",
    20: "A Dubious Track",
    21: "HereInMyGarage",
    22: "Benjamin",
    23: "Gravity Diner",
    24: "WhomTheBellToll",
    25: "The True End",
    26: "The Old Mine",
    27: "The need 4 speed",
    28: "IT'S ALIVE!",
    29: "DK Mountain",
    30: "T.R.D Raceway",
    31: "LuxÆterna",
    32: "Speed Freak",
    33: "Rocky Falls",
    34: "Ye Ol' Mine",
    35: "Wacky House",
    36: "Back At It",
    37: "The Wheel...",
    38: "Octoblast",
    39: "Speed of Rwar",
    40: "Slam Dunk",
    41: "VivaLasVengance",
    42: "Hidden Ally",
    43: "Drive",
    44: "Bell O' Clock",
    45: "Dirty Waters",
    46: "SunriseOverdrive",
    47: "Random Raceway",
    48: "Sharks...",
    49: "Victorious",
    50: "BANG!",
    51: "Karma",
    52: "Less Than Zero",
    53: "Lost In My Mind",
    54: "TheGreatestShow",
    55: "Yes, I'm A Mess",
    56: "The Dumb Track",
    57: "Luck N'Re-load",
    58: "Delivery Duel",
    59: "Panic Picnic",
    60: "Paint It, Red",
    61: "Stats of Champs",
    62: "BackyardShowdwn",
    63: "Drift Away",
    64: "George Clooney",
    65: "The Aftermath",
    66: "InsertTrackName",
    67: "Surprise Attack",
    68: "Blitzen's Test",
    69: "Dashin Through",
    70: "Home Alone",
    71: "Sleigh Bells",
    72: "Heat Miser",
    73: "Snow Miser",
    74: "OChristmasTree",
    75: "Ain't no 16-bit",
    76: "HW35 Set",
    77: "Hungering Deep",
    78: "Midnite Joyride",
    79: "TheAbysReturens",
    80: "Octopus Attack",
    81: "Turn Back Time",
    82: "Right Back at U",
    83: "H.Y.C.Y.BH?",
    84: "Burning Rubber",
    85: "It's High Noon",
    86: "Drifting Crazy",
    87: "Game Over",
    88: "Drive-Thru",
    89: "Spin Eternally",
    90: "Rev the Engines",
    91: "Goosebumps",
    92: "Circus Stunt",
  };

  const wolf = {
    1: "Ratatata!",
    2: "SomethingCheeky",
    3: "FFzah, Wolfstyle",
    4: "ILostMy10mm!!!!",
    5: "The Trixster",
    6: "Den of the Wolf",
    7: "AirDriveGP",
    8: "NextLap Raceway",
    9: "ByzanBiscuits",
    10: "El Dorado GP",
    11: "Felon's Run",
    12: "Power Train!",
    13: "AllGunsBlazing",
    14: "AintNoSunshine2",
    15: "DreadLord",
    16: "WeAreTheFire!",
    17: "She's A Roller",
    18: "The Switchback",
    19: "Kivetmetsan",
    20: "WRU Speedway",
    21: "HEVYMETALVIKING",
    22: "BlackTopBlitz",
    23: "The Rocktopus",
    24: "HighRise GP",
    25: "WildUno!",
    26: "Vice Grip City",
    27: "Order of Fear",
    28: "VisitorsAmongUs",
    29: "Madison Blues",
    30: "Labtech Inc.",
    31: "Modus Request",
    32: "The Wolf",
    33: "K.W.Groovie!",
    34: "KSA'77",
    35: "The Molina 652",
    36: "ChinCheckPuta!",
    37: "Berserkir",
    38: "Interstellar",
    39: "Bad 2 The Bone",
    40: "The Seeker",
    41: "The Wanderer",
    42: "Paint It,Black",
    43: "When In Rome...",
    44: "Sicilian Stomp!",
    45: "ItsNotDelivery",
    46: "StreetBeast!",
    47: "MidwestXC",
    48: "BadGasGoesFast",
    49: "PumpRush GP",
    50: "Perimter GP",
  };

  const yota = {
    1: "Bomber Ally",
    2: "Explosive Mix",
    3: "Pressure Carbon",
    4: "Timmy's Pasta",
    5: "Counter Dash",
    6: "Owl of Socorro",
    7: "Elephant Butte",
    8: "CloudCroft Mt",
    9: "Silver Plateau",
    10: "Carlsbad Cavern",
    11: "Speed Wagon FD",
    12: "Bourbon Rush",
    13: "Roof Rumble",
    14: "Take This L",
    15: "Wall Runner",
    16: "Cliff Complex",
    17: "DownTownCircuit",
    18: "HighScore Rally",
    19: "Rocky Road",
    20: "Collision Drift",
    21: "Mist Mountain",
    22: "Space out",
    23: "Vapor City",
    24: "Timmy Vented",
    25: "Tree to Tree",
    26: "Mineshaft Sprit",
    27: "Semi-Loop",
    28: "2nd Floor Rally",
    29: "Roof Rally",
    30: "Shiprock Canyon",
    31: "Lead Or Premium",
    32: "Draftghetti",
    33: "Dwarf Star",
    34: "Equation of Pi",
    35: "Satellite Fuse",
    36: "Last Flare",
    37: "SpaceDust Rally",
    38: "Atmosphere Dash",
    39: "Lift Off In",
    40: "Doc Ock Battle",
    41: "Patio Rush",
    42: "Down Rise",
    43: "Mountain Bash",
    44: "Wall Runners",
    45: "Ceiling Circus",
    46: "Surfing Curves",
    47: "Shelf Shuffle",
    48: "Outdoor Ruckus",
    49: "High Rise",
    50: "Simple Race 3",
    51: "Simple Race 2",
    52: "Simple Race 1",
    53: "Semi-Canyon",
    54: "Semi Cliff",
    55: "Diamante Bruto",
    56: "UFO Rush",
    57: "Vent B",
    58: "Satellite City",
    59: "Cloud 9",
    60: "Yota's Training",
    61: "dino boneyard",
    62: "terror saur",
  };

  // ---------- Track collection registry ----------
  // `prefix` + each track's local id above combine into a global id
  // (prefix * 1000 + localId) in app.js's buildGame2Tracks(). To drop a
  // creator's tracks from the game entirely, just comment out their
  // line below with // -- the `const` object above can stay as-is.
  const trackCollections = {
    // "Acceler":    { prefix:  1, tracks: acceler },
    // "Animax":     { prefix:  2, tracks: animax },
    "Beck":       { prefix:  3, tracks: beck },
    "Biyzor":     { prefix:  4, tracks: biyzor },
    "Bread":      { prefix:  5, tracks: bread },
    // "Copper":     { prefix:  6, tracks: copper },
    // "CruX":       { prefix:  7, tracks: crux },
    "Dandube":    { prefix:  9, tracks: dandube },
    "Dish":       { prefix: 10, tracks: dish },
    "Dr.Cr":      { prefix: 11, tracks: drcr },
    // "Elias":      { prefix: 12, tracks: elias },
    // "Emily":      { prefix: 13, tracks: emily },
    "F1Wolf":     { prefix: 14, tracks: f1wolf },
    "Fidestic":   { prefix: 15, tracks: fidestic },
    "Frost":      { prefix: 16, tracks: frost },
    // "Garnarbles": { prefix: 17, tracks: garnarbles },
    "Gore":       { prefix: 18, tracks: gore },
    "Gunner":     { prefix: 19, tracks: gunner },
    "Juampee":    { prefix: 20, tracks: juampee },
    "Judge":      { prefix: 21, tracks: judge },
    // "Kami":       { prefix: 22, tracks: kami },
    "Kiko":       { prefix: 23, tracks: kiko },
    "Mickey":     { prefix: 24, tracks: mickey },
    // "Mog":        { prefix: 25, tracks: mog },
    "Pato":       { prefix: 26, tracks: pato },
    // "Q5rap":      { prefix: 27, tracks: q5rap },
    // "RJ":         { prefix: 28, tracks: rj },
    "Shatter":    { prefix: 29, tracks: shatter },
    "Swole":      { prefix: 30, tracks: swole },
    "TRD":        { prefix: 31, tracks: trd },
    "Wolf":       { prefix: 32, tracks: wolf },
    // "Yota":       { prefix: 33, tracks: yota },
  };

  return { game2Cars, trackCollections };
})();

// app.js reads `trackCollections` (not a flat array) and flattens it into
// game2Tracks at load time via buildGame2Tracks() -- see app.js.
